import { useState, useEffect, useMemo } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Plus, ArrowDownToLine, Trash2, Sparkles, Check, FileText, Leaf, Factory, ChevronDown, ChevronRight, Calendar } from "lucide-react";
import { usePenjualanPetani } from "@/hooks/use-penjualan-petani";
import { usePengepul } from "@/hooks/use-pengepul";
import { useFarmers } from "@/hooks/use-farmers";
import { TableSkeleton } from "@/components/ui/skeleton-templates";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { format, addDays } from "date-fns";
import { id as localeId } from "date-fns/locale";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { SavedEstimation, FarmerWeeklyData, DailyData } from "@/hooks/use-harvest-estimation";

interface WeekData {
  estimationId: string;
  estimationName: string;
  weekIndex: number;
  weekLabel: string;
  startDate: string;
  endDate: string;
  farmersOrganic: FarmerWeekEntry[];
  farmersConventional: FarmerWeekEntry[];
  totalOrganic: number;
  totalConventional: number;
  isProcessed: boolean;
}

interface FarmerWeekEntry {
  farmerId: string;
  farmerName: string;
  farmerCode: string;
  pengepulId: string;
  pengepulName: string;
  dailyValues: number[];
  dailyDates: string[];
  total: number;
  isOrganic: boolean;
}

interface EstimationGroup {
  estimationName: string;
  estimationId: string;
  weeks: WeekData[];
  count: number;
  totalKg: number;
  ids: string[];
}

export const BarangMasukTab = () => {
  const { penjualanList, loading, addPenjualan, deletePenjualan, refetch } = usePenjualanPetani();
  const { pengepulList } = usePengepul();
  const { farmers } = useFarmers();
  
  const [dialogOpen, setDialogOpen] = useState(false);
  const [autoGenerateDialogOpen, setAutoGenerateDialogOpen] = useState(false);
  const [filterPengepul, setFilterPengepul] = useState<string>("all");
  const [selectedWeeks, setSelectedWeeks] = useState<Set<string>>(new Set());
  const [autoGenerateLoading, setAutoGenerateLoading] = useState(false);
  const [savedEstimations, setSavedEstimations] = useState<SavedEstimation[]>([]);
  const [isLoadingEstimations, setIsLoadingEstimations] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [deletingEstimation, setDeletingEstimation] = useState<EstimationGroup | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [expandedWeeks, setExpandedWeeks] = useState<Set<string>>(new Set());
  
  const [form, setForm] = useState({
    pengepul_id: "",
    petani_id: "",
    tanggal_jual: format(new Date(), "yyyy-MM-dd"),
    jumlah_kg: "",
    harga_per_kg: "",
    warna_produk: "",
    kualitas: "grade_a",
    catatan: "",
    is_organic: true,
  });

  // Load saved estimations
  useEffect(() => {
    const loadEstimations = async () => {
      setIsLoadingEstimations(true);
      try {
        const { data, error } = await supabase
          .from("estimasi_panen")
          .select("*")
          .order("created_at", { ascending: false });

        if (error) throw error;
        setSavedEstimations(data as unknown as SavedEstimation[]);
      } catch (error) {
        console.error("Error loading estimations:", error);
      } finally {
        setIsLoadingEstimations(false);
      }
    };
    loadEstimations();
  }, []);

  const resetForm = () => {
    setForm({
      pengepul_id: "",
      petani_id: "",
      tanggal_jual: format(new Date(), "yyyy-MM-dd"),
      jumlah_kg: "",
      harga_per_kg: "",
      warna_produk: "",
      kualitas: "grade_a",
      catatan: "",
      is_organic: true,
    });
  };

  // Filter farmers by selected pengepul
  const filteredFarmers = farmers.filter(f => f.pengepul_id === form.pengepul_id);

  // Auto-fill harga when pengepul is selected
  const handlePengepulChange = (pengepulId: string) => {
    const pengepul = pengepulList.find(p => p.id === pengepulId);
    setForm(prev => ({
      ...prev,
      pengepul_id: pengepulId,
      petani_id: "",
      harga_per_kg: pengepul ? String(pengepul.harga_beli) : "",
    }));
  };

  const handleSubmit = async () => {
    if (!form.pengepul_id || !form.petani_id || !form.jumlah_kg || !form.harga_per_kg) return;

    await addPenjualan({
      pengepul_id: form.pengepul_id,
      petani_id: form.petani_id,
      tanggal_jual: form.tanggal_jual,
      jumlah_kg: parseFloat(form.jumlah_kg),
      harga_per_kg: parseFloat(form.harga_per_kg),
      warna_produk: form.warna_produk || null,
      kualitas: form.kualitas,
      catatan: form.catatan || null,
      is_organic: form.is_organic,
    } as any);

    resetForm();
    setDialogOpen(false);
  };

  const handleDelete = async (id: string) => {
    if (confirm("Yakin ingin menghapus data ini?")) {
      await deletePenjualan(id);
    }
  };

  // Process estimations into week-based structure
  const weeklyEstimationData = useMemo((): WeekData[] => {
    const weeks: WeekData[] = [];

    savedEstimations.forEach(estimation => {
      const panenData = estimation.data_panen as unknown as Array<{
        weekIndex: number;
        startDate: string;
        endDate: string;
        farmersData: FarmerWeeklyData[];
        holidays: number[];
      }>;

      if (!panenData) return;

      panenData.forEach(week => {
        const farmersOrganic: FarmerWeekEntry[] = [];
        const farmersConventional: FarmerWeekEntry[] = [];

        week.farmersData.forEach(farmerData => {
          const farmer = farmers.find(f => f.id === farmerData.farmerId);
          if (!farmer || !farmer.pengepul_id) return;

          const pengepul = pengepulList.find(p => p.id === farmer.pengepul_id);
          if (!pengepul) return;

          const dailyValues = farmerData.dailySales.map(d => d.value);
          const dailyDates = farmerData.dailySales.map(d => d.date);
          const total = dailyValues.reduce((sum, v) => sum + v, 0);
          const isOrganic = farmerData.isOrganic !== false;

          const entry: FarmerWeekEntry = {
            farmerId: farmerData.farmerId,
            farmerName: farmerData.farmerName,
            farmerCode: farmerData.farmerCode,
            pengepulId: farmer.pengepul_id,
            pengepulName: pengepul.nama,
            dailyValues,
            dailyDates,
            total,
            isOrganic,
          };

          if (isOrganic) {
            farmersOrganic.push(entry);
          } else {
            farmersConventional.push(entry);
          }
        });

        // Check if this week is already processed
        const isProcessed = farmersOrganic.concat(farmersConventional).some(entry => {
          return entry.dailyDates.some(date => {
            return penjualanList.some(p => 
              p.petani_id === entry.farmerId && 
              p.tanggal_jual === date &&
              p.catatan?.includes(estimation.nama_estimasi)
            );
          });
        });

        weeks.push({
          estimationId: estimation.id,
          estimationName: estimation.nama_estimasi,
          weekIndex: week.weekIndex,
          weekLabel: `Minggu ${week.weekIndex + 1}`,
          startDate: week.startDate,
          endDate: week.endDate,
          farmersOrganic,
          farmersConventional,
          totalOrganic: farmersOrganic.reduce((sum, f) => sum + f.total, 0),
          totalConventional: farmersConventional.reduce((sum, f) => sum + f.total, 0),
          isProcessed,
        });
      });
    });

    return weeks.sort((a, b) => a.startDate.localeCompare(b.startDate));
  }, [savedEstimations, farmers, pengepulList, penjualanList]);

  // Get unprocessed weeks
  const unprocessedWeeks = weeklyEstimationData.filter(w => !w.isProcessed);

  const toggleWeek = (weekKey: string) => {
    setExpandedWeeks(prev => {
      const newSet = new Set(prev);
      if (newSet.has(weekKey)) {
        newSet.delete(weekKey);
      } else {
        newSet.add(weekKey);
      }
      return newSet;
    });
  };

  const handleToggleWeekSelection = (weekKey: string) => {
    setSelectedWeeks(prev => {
      const newSet = new Set(prev);
      if (newSet.has(weekKey)) {
        newSet.delete(weekKey);
      } else {
        newSet.add(weekKey);
      }
      return newSet;
    });
  };

  const handleSelectAllWeeks = () => {
    if (selectedWeeks.size === unprocessedWeeks.length) {
      setSelectedWeeks(new Set());
    } else {
      setSelectedWeeks(new Set(unprocessedWeeks.map(w => `${w.estimationId}-${w.weekIndex}`)));
    }
  };

  const handleAutoGenerate = async () => {
    if (selectedWeeks.size === 0) {
      toast({
        title: "Pilih Minggu",
        description: "Pilih minimal satu minggu untuk diproses",
        variant: "destructive",
      });
      return;
    }

    setAutoGenerateLoading(true);
    let successCount = 0;
    let errorCount = 0;

    for (const weekKey of selectedWeeks) {
      const week = weeklyEstimationData.find(w => `${w.estimationId}-${w.weekIndex}` === weekKey);
      if (!week) continue;

      const allFarmers = [...week.farmersOrganic, ...week.farmersConventional];

      for (const farmerEntry of allFarmers) {
        const pengepul = pengepulList.find(p => p.id === farmerEntry.pengepulId);
        if (!pengepul) continue;

        // Create entry for each day with value > 0
        for (let i = 0; i < farmerEntry.dailyValues.length; i++) {
          const value = farmerEntry.dailyValues[i];
          const date = farmerEntry.dailyDates[i];
          
          if (value <= 0) continue;

          // Check if already exists
          const exists = penjualanList.some(p => 
            p.petani_id === farmerEntry.farmerId && 
            p.tanggal_jual === date &&
            Math.abs(Number(p.jumlah_kg) - value) < 0.1
          );

          if (exists) continue;

          const result = await addPenjualan({
            pengepul_id: farmerEntry.pengepulId,
            petani_id: farmerEntry.farmerId,
            tanggal_jual: date,
            jumlah_kg: value,
            harga_per_kg: pengepul.harga_beli,
            warna_produk: null,
            kualitas: "grade_a",
            catatan: `Auto-generated dari estimasi: ${week.estimationName} - ${week.weekLabel}`,
            is_organic: farmerEntry.isOrganic,
          } as any);

          if (result) {
            successCount++;
          } else {
            errorCount++;
          }
        }
      }
    }

    setAutoGenerateLoading(false);
    setSelectedWeeks(new Set());
    setAutoGenerateDialogOpen(false);
    refetch();

    if (successCount > 0) {
      toast({
        title: "Berhasil",
        description: `${successCount} data penjualan berhasil dibuat dari estimasi`,
      });
    }
    if (errorCount > 0) {
      toast({
        title: "Sebagian Gagal",
        description: `${errorCount} data gagal diproses`,
        variant: "destructive",
      });
    }
  };

  // Group processed entries by estimation
  const estimationGroups = useMemo((): EstimationGroup[] => {
    const groups: { [key: string]: EstimationGroup } = {};
    
    penjualanList.forEach(item => {
      if (item.catatan && item.catatan.includes("Auto-generated dari estimasi:")) {
        const match = item.catatan.match(/Auto-generated dari estimasi: (.+?) - Minggu/);
        if (match) {
          const estimationName = match[1];
          if (!groups[estimationName]) {
            const estimation = savedEstimations.find(e => e.nama_estimasi === estimationName);
            groups[estimationName] = {
              estimationName,
              estimationId: estimation?.id || '',
              weeks: [],
              count: 0,
              totalKg: 0,
              ids: [],
            };
          }
          groups[estimationName].count++;
          groups[estimationName].totalKg += Number(item.jumlah_kg);
          groups[estimationName].ids.push(item.id);
        }
      }
    });

    return Object.values(groups).sort((a, b) => b.count - a.count);
  }, [penjualanList, savedEstimations]);

  const handleDeleteEstimationGroup = async () => {
    if (!deletingEstimation) return;

    setIsDeleting(true);
    let successCount = 0;
    let errorCount = 0;

    for (const id of deletingEstimation.ids) {
      const success = await deletePenjualan(id);
      if (success) {
        successCount++;
      } else {
        errorCount++;
      }
    }

    setIsDeleting(false);
    setDeleteDialogOpen(false);
    setDeletingEstimation(null);
    refetch();

    if (successCount > 0) {
      toast({
        title: "Berhasil Dihapus",
        description: `${successCount} data dari estimasi "${deletingEstimation.estimationName}" berhasil dihapus`,
      });
    }
    if (errorCount > 0) {
      toast({
        title: "Sebagian Gagal",
        description: `${errorCount} data gagal dihapus`,
        variant: "destructive",
      });
    }
  };

  // Filter and group display data by week
  const displayWeeks = useMemo(() => {
    const filtered = filterPengepul === "all" 
      ? penjualanList 
      : penjualanList.filter(p => p.pengepul_id === filterPengepul);

    // Group by week (based on catatan)
    const weekMap = new Map<string, {
      weekLabel: string;
      estimationName: string;
      organic: typeof penjualanList;
      conventional: typeof penjualanList;
    }>();

    filtered.forEach(item => {
      const match = item.catatan?.match(/Auto-generated dari estimasi: (.+?) - (Minggu \d+)/);
      if (match) {
        const [, estName, weekLabel] = match;
        const key = `${estName}-${weekLabel}`;
        
        if (!weekMap.has(key)) {
          weekMap.set(key, {
            weekLabel,
            estimationName: estName,
            organic: [],
            conventional: [],
          });
        }
        
        const group = weekMap.get(key)!;
        if ((item as any).is_organic !== false) {
          group.organic.push(item);
        } else {
          group.conventional.push(item);
        }
      }
    });

    return Array.from(weekMap.entries()).map(([key, value]) => ({
      key,
      ...value,
    }));
  }, [penjualanList, filterPengepul]);

  // Render farmer table for a list
  const renderFarmerTable = (list: typeof penjualanList, title: string, icon: React.ReactNode) => {
    // Group by farmer
    const farmerMap = new Map<string, {
      nama: string;
      kode: string;
      dailyData: { date: string; value: number }[];
      total: number;
    }>();

    list.forEach(item => {
      const farmerId = item.petani_id;
      if (!farmerMap.has(farmerId)) {
        farmerMap.set(farmerId, {
          nama: item.petani?.nama || 'Unknown',
          kode: item.petani?.kode_petani || '-',
          dailyData: [],
          total: 0,
        });
      }
      const farmer = farmerMap.get(farmerId)!;
      farmer.dailyData.push({
        date: item.tanggal_jual,
        value: Number(item.jumlah_kg),
      });
      farmer.total += Number(item.jumlah_kg);
    });

    const farmers = Array.from(farmerMap.values());
    const totalAll = farmers.reduce((sum, f) => sum + f.total, 0);

    if (farmers.length === 0) return null;

    return (
      <div className="space-y-2">
        <div className="flex items-center gap-2 text-sm font-medium">
          {icon}
          <span>{title}</span>
          <Badge variant="outline">{farmers.length} petani</Badge>
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Nama Petani</TableHead>
              <TableHead>Kode</TableHead>
              <TableHead className="text-right">Total (Kg)</TableHead>
              <TableHead className="text-right">Aksi</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {farmers.map((farmer, idx) => (
              <TableRow key={idx}>
                <TableCell className="font-medium">{farmer.nama}</TableCell>
                <TableCell>{farmer.kode}</TableCell>
                <TableCell className="text-right">{farmer.total.toLocaleString()}</TableCell>
                <TableCell className="text-right">
                  <Button 
                    variant="ghost" 
                    size="icon"
                    onClick={() => {
                      const itemsToDelete = list.filter(i => i.petani_id === list.find(l => l.petani?.nama === farmer.nama)?.petani_id);
                      itemsToDelete.forEach(item => handleDelete(item.id));
                    }}
                  >
                    <Trash2 className="h-4 w-4 text-destructive" />
                  </Button>
                </TableCell>
              </TableRow>
            ))}
            <TableRow className="bg-muted/50">
              <TableCell colSpan={2} className="font-bold">Total</TableCell>
              <TableCell className="text-right font-bold">{totalAll.toLocaleString()} Kg</TableCell>
              <TableCell></TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    );
  };

  if (loading) {
    return <TableSkeleton rows={5} columns={6} />;
  }

  return (
    <div className="space-y-6">
      {/* Header Card */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between flex-wrap gap-4">
          <div>
            <CardTitle className="flex items-center gap-2">
              <ArrowDownToLine className="h-5 w-5" />
              Barang Masuk
            </CardTitle>
            <CardDescription>Penjualan petani ke pengepul dari data estimasi (per minggu)</CardDescription>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            <Select value={filterPengepul} onValueChange={setFilterPengepul}>
              <SelectTrigger className="w-48">
                <SelectValue placeholder="Filter Pengepul" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Semua Pengepul</SelectItem>
                {pengepulList.map((p) => (
                  <SelectItem key={p.id} value={p.id}>{p.nama}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            
            {/* Delete per Estimation */}
            {estimationGroups.length > 0 && (
              <Button
                variant="outline"
                className="border-destructive text-destructive hover:bg-destructive/10"
                onClick={() => setDeleteDialogOpen(true)}
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Hapus per Estimasi ({estimationGroups.length})
              </Button>
            )}
            
            {/* Auto Generate Dialog */}
            <Dialog open={autoGenerateDialogOpen} onOpenChange={(open) => {
              setAutoGenerateDialogOpen(open);
              if (!open) {
                setSelectedWeeks(new Set());
              }
            }}>
              <DialogTrigger asChild>
                <Button variant="outline" className="border-primary text-primary hover:bg-primary/10">
                  <Sparkles className="h-4 w-4 mr-2" />
                  Auto Generate
                  {unprocessedWeeks.length > 0 && (
                    <span className="ml-2 bg-primary text-primary-foreground px-2 py-0.5 rounded-full text-xs">
                      {unprocessedWeeks.length} minggu
                    </span>
                  )}
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-5xl max-h-[85vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle className="flex items-center gap-2">
                    <Sparkles className="h-5 w-5 text-primary" />
                    Auto Generate dari Estimasi Panen
                  </DialogTitle>
                  <DialogDescription>
                    Pilih minggu yang akan diproses. Data penjualan akan dibuat per petani per hari.
                  </DialogDescription>
                </DialogHeader>

                {isLoadingEstimations ? (
                  <div className="text-center py-8">
                    <p className="text-muted-foreground">Memuat data estimasi...</p>
                  </div>
                ) : savedEstimations.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    <FileText className="h-12 w-12 mx-auto mb-3 opacity-50" />
                    <p className="font-medium">Belum ada data estimasi tersimpan</p>
                    <p className="text-sm">Buat dan simpan estimasi penjualan di tab Estimasi terlebih dahulu</p>
                  </div>
                ) : unprocessedWeeks.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    <Check className="h-12 w-12 mx-auto mb-3 text-green-500" />
                    <p className="font-medium">Semua minggu sudah diproses</p>
                    <p className="text-sm">Tidak ada data baru yang perlu dikonversi</p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {/* Select All */}
                    <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                      <div className="flex items-center gap-2">
                        <Checkbox
                          checked={selectedWeeks.size === unprocessedWeeks.length}
                          onCheckedChange={handleSelectAllWeeks}
                        />
                        <span className="font-medium">Pilih Semua Minggu ({unprocessedWeeks.length})</span>
                      </div>
                      <Button 
                        onClick={handleAutoGenerate} 
                        disabled={selectedWeeks.size === 0 || autoGenerateLoading}
                      >
                        {autoGenerateLoading ? "Memproses..." : `Generate ${selectedWeeks.size} Minggu`}
                      </Button>
                    </div>

                    {/* Week Cards */}
                    {unprocessedWeeks.map(week => {
                      const weekKey = `${week.estimationId}-${week.weekIndex}`;
                      const isExpanded = expandedWeeks.has(weekKey);
                      const isSelected = selectedWeeks.has(weekKey);

                      return (
                        <Collapsible key={weekKey} open={isExpanded} onOpenChange={() => toggleWeek(weekKey)}>
                          <Card className={isSelected ? "border-primary" : ""}>
                            <CardHeader className="py-3">
                              <div className="flex items-center justify-between">
                                <div className="flex items-center gap-3">
                                  <Checkbox
                                    checked={isSelected}
                                    onCheckedChange={() => handleToggleWeekSelection(weekKey)}
                                  />
                                  <CollapsibleTrigger asChild>
                                    <Button variant="ghost" size="icon" className="h-6 w-6">
                                      {isExpanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
                                    </Button>
                                  </CollapsibleTrigger>
                                  <div>
                                    <p className="font-medium">{week.estimationName} - {week.weekLabel}</p>
                                    <p className="text-sm text-muted-foreground flex items-center gap-1">
                                      <Calendar className="h-3 w-3" />
                                      {format(new Date(week.startDate), "dd MMM", { locale: localeId })} - {format(new Date(week.endDate), "dd MMM yyyy", { locale: localeId })}
                                    </p>
                                  </div>
                                </div>
                                <div className="flex items-center gap-4">
                                  <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                                    <Leaf className="h-3 w-3 mr-1" />
                                    {week.totalOrganic.toLocaleString()} Kg
                                  </Badge>
                                  <Badge variant="outline" className="bg-orange-50 text-orange-700 border-orange-200">
                                    <Factory className="h-3 w-3 mr-1" />
                                    {week.totalConventional.toLocaleString()} Kg
                                  </Badge>
                                </div>
                              </div>
                            </CardHeader>
                            <CollapsibleContent>
                              <CardContent className="pt-0">
                                <div className="grid grid-cols-2 gap-6">
                                  {/* Organic Table */}
                                  {week.farmersOrganic.length > 0 && (
                                    <div className="space-y-2">
                                      <div className="flex items-center gap-2 text-sm font-medium text-green-700">
                                        <Leaf className="h-4 w-4" />
                                        Produk Organik ({week.farmersOrganic.length} petani)
                                      </div>
                                      <Table>
                                        <TableHeader>
                                          <TableRow>
                                            <TableHead>Nama Petani</TableHead>
                                            <TableHead>Kode</TableHead>
                                            {[1, 2, 3, 4, 5, 6, 7].map(d => (
                                              <TableHead key={d} className="text-center w-12">H{d}</TableHead>
                                            ))}
                                            <TableHead className="text-right">Total</TableHead>
                                          </TableRow>
                                        </TableHeader>
                                        <TableBody>
                                          {week.farmersOrganic.map(farmer => (
                                            <TableRow key={farmer.farmerId}>
                                              <TableCell className="font-medium">{farmer.farmerName}</TableCell>
                                              <TableCell>{farmer.farmerCode}</TableCell>
                                              {farmer.dailyValues.map((val, idx) => (
                                                <TableCell key={idx} className="text-center text-sm">
                                                  {val > 0 ? val.toLocaleString() : '-'}
                                                </TableCell>
                                              ))}
                                              <TableCell className="text-right font-bold">{farmer.total.toLocaleString()}</TableCell>
                                            </TableRow>
                                          ))}
                                        </TableBody>
                                      </Table>
                                    </div>
                                  )}

                                  {/* Conventional Table */}
                                  {week.farmersConventional.length > 0 && (
                                    <div className="space-y-2">
                                      <div className="flex items-center gap-2 text-sm font-medium text-orange-700">
                                        <Factory className="h-4 w-4" />
                                        Produk Konvensional ({week.farmersConventional.length} petani)
                                      </div>
                                      <Table>
                                        <TableHeader>
                                          <TableRow>
                                            <TableHead>Nama Petani</TableHead>
                                            <TableHead>Kode</TableHead>
                                            {[1, 2, 3, 4, 5, 6, 7].map(d => (
                                              <TableHead key={d} className="text-center w-12">H{d}</TableHead>
                                            ))}
                                            <TableHead className="text-right">Total</TableHead>
                                          </TableRow>
                                        </TableHeader>
                                        <TableBody>
                                          {week.farmersConventional.map(farmer => (
                                            <TableRow key={farmer.farmerId}>
                                              <TableCell className="font-medium">{farmer.farmerName}</TableCell>
                                              <TableCell>{farmer.farmerCode}</TableCell>
                                              {farmer.dailyValues.map((val, idx) => (
                                                <TableCell key={idx} className="text-center text-sm">
                                                  {val > 0 ? val.toLocaleString() : '-'}
                                                </TableCell>
                                              ))}
                                              <TableCell className="text-right font-bold">{farmer.total.toLocaleString()}</TableCell>
                                            </TableRow>
                                          ))}
                                        </TableBody>
                                      </Table>
                                    </div>
                                  )}
                                </div>
                              </CardContent>
                            </CollapsibleContent>
                          </Card>
                        </Collapsible>
                      );
                    })}
                  </div>
                )}
              </DialogContent>
            </Dialog>

            <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
              <DialogTrigger asChild>
                <Button className="bg-gradient-organic">
                  <Plus className="h-4 w-4 mr-2" />
                  Tambah Manual
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Tambah Barang Masuk Manual</DialogTitle>
                  <DialogDescription>Input penjualan petani ke pengepul secara manual</DialogDescription>
                </DialogHeader>
                <div className="space-y-4">
                  <div>
                    <Label>Pengepul *</Label>
                    <Select value={form.pengepul_id} onValueChange={handlePengepulChange}>
                      <SelectTrigger><SelectValue placeholder="Pilih pengepul" /></SelectTrigger>
                      <SelectContent>
                        {pengepulList.map(p => (
                          <SelectItem key={p.id} value={p.id}>{p.nama}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label>Petani *</Label>
                    <Select value={form.petani_id} onValueChange={(v) => setForm(prev => ({ ...prev, petani_id: v }))}>
                      <SelectTrigger><SelectValue placeholder="Pilih petani" /></SelectTrigger>
                      <SelectContent>
                        {filteredFarmers.map(f => (
                          <SelectItem key={f.id} value={f.id}>{f.nama} ({f.kode_petani})</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label>Tanggal Jual</Label>
                      <Input type="date" value={form.tanggal_jual} onChange={e => setForm(prev => ({ ...prev, tanggal_jual: e.target.value }))} />
                    </div>
                    <div>
                      <Label>Jumlah (Kg) *</Label>
                      <Input type="number" value={form.jumlah_kg} onChange={e => setForm(prev => ({ ...prev, jumlah_kg: e.target.value }))} />
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label>Harga/Kg *</Label>
                      <Input type="number" value={form.harga_per_kg} onChange={e => setForm(prev => ({ ...prev, harga_per_kg: e.target.value }))} />
                    </div>
                    <div>
                      <Label>Tipe Produk</Label>
                      <Select value={form.is_organic ? "organic" : "conventional"} onValueChange={v => setForm(prev => ({ ...prev, is_organic: v === "organic" }))}>
                        <SelectTrigger><SelectValue /></SelectTrigger>
                        <SelectContent>
                          <SelectItem value="organic">Organik</SelectItem>
                          <SelectItem value="conventional">Konvensional</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <Button onClick={handleSubmit} className="w-full">Simpan</Button>
                </div>
              </DialogContent>
            </Dialog>
          </div>
        </CardHeader>
      </Card>

      {/* Delete Estimation Dialog */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Hapus Data Estimasi</AlertDialogTitle>
            <AlertDialogDescription>
              Pilih estimasi yang datanya akan dihapus dari barang masuk.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="space-y-2 max-h-64 overflow-y-auto">
            {estimationGroups.map(group => (
              <div
                key={group.estimationName}
                className={`p-3 border rounded-lg cursor-pointer hover:border-destructive ${deletingEstimation?.estimationName === group.estimationName ? 'border-destructive bg-destructive/5' : ''}`}
                onClick={() => setDeletingEstimation(group)}
              >
                <div className="font-medium">{group.estimationName}</div>
                <div className="text-sm text-muted-foreground">
                  {group.count} entri • {group.totalKg.toLocaleString()} Kg
                </div>
              </div>
            ))}
          </div>
          <AlertDialogFooter>
            <AlertDialogCancel>Batal</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDeleteEstimationGroup}
              disabled={!deletingEstimation || isDeleting}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {isDeleting ? "Menghapus..." : "Hapus"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Display Data per Week */}
      {penjualanList.length === 0 ? (
        <Card className="p-8 text-center text-muted-foreground">
          <ArrowDownToLine className="h-12 w-12 mx-auto mb-3 opacity-50" />
          <p className="font-medium">Belum ada data barang masuk</p>
          <p className="text-sm">Gunakan Auto Generate untuk membuat data dari estimasi penjualan</p>
        </Card>
      ) : (
        <div className="space-y-4">
          {displayWeeks.map(weekGroup => (
            <Card key={weekGroup.key}>
              <CardHeader className="py-3">
                <CardTitle className="text-lg flex items-center gap-2">
                  <Calendar className="h-5 w-5" />
                  {weekGroup.estimationName} - {weekGroup.weekLabel}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-6">
                  {renderFarmerTable(
                    weekGroup.organic,
                    "Produk Organik",
                    <Leaf className="h-4 w-4 text-green-600" />
                  )}
                  {renderFarmerTable(
                    weekGroup.conventional,
                    "Produk Konvensional",
                    <Factory className="h-4 w-4 text-orange-500" />
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};
