import { useState, useEffect, useMemo } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Checkbox } from "@/components/ui/checkbox";
import { Plus, ArrowUpFromLine, Trash2, Wand2, AlertCircle, ChevronDown, ChevronRight, Leaf, Factory, Calendar, FileText, Check } from "lucide-react";
import { usePengambilanKoperasi } from "@/hooks/use-pengambilan-koperasi";
import { usePenjualanPetani } from "@/hooks/use-penjualan-petani";
import { usePengepul } from "@/hooks/use-pengepul";
import { useFarmers } from "@/hooks/use-farmers";
import { TableSkeleton } from "@/components/ui/skeleton-templates";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { format, addDays, startOfDay, isAfter } from "date-fns";
import { id as localeId } from "date-fns/locale";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { SavedEstimation, FarmerWeeklyData, DailyData } from "@/hooks/use-harvest-estimation";

interface WeekData {
  estimationId: string;
  estimationName: string;
  weekIndex: number;
  weekLabel: string;
  startDate: string;
  endDate: string;
  pickupDate: string;
  farmersOrganic: FarmerWeekEntry[];
  farmersConventional: FarmerWeekEntry[];
  totalOrganic: number;
  totalConventional: number;
  isProcessed: boolean;
}

interface FarmerWeekEntry {
  farmerId: string;
  farmerName: string;
  farmerCode: string;
  pengepulId: string;
  pengepulName: string;
  dailyValues: number[];
  total: number;
  isOrganic: boolean;
}

interface DisplayLot {
  lotKey: string;
  estimationName: string;
  weekLabel: string;
  startDate: string;
  endDate: string;
  isOrganic: boolean;
  farmers: {
    petani_id: string;
    petani_nama: string;
    petani_kode: string;
    jumlah_kg: number;
  }[];
  totalKg: number;
  items: Array<{
    id: string;
    pengepul_nama: string;
    jumlah_kg: number;
  }>;
}

export const BarangKeluarTab = () => {
  const { pengambilanList, loading, addPengambilan, deletePengambilan, refetch } = usePengambilanKoperasi();
  const { penjualanList } = usePenjualanPetani();
  const { pengepulList } = usePengepul();
  const { farmers } = useFarmers();
  
  const [dialogOpen, setDialogOpen] = useState(false);
  const [autoGenerateDialogOpen, setAutoGenerateDialogOpen] = useState(false);
  const [filterPengepul, setFilterPengepul] = useState<string>("all");
  const [generatingAuto, setGeneratingAuto] = useState(false);
  const [expandedLots, setExpandedLots] = useState<Set<string>>(new Set());
  
  const [savedEstimations, setSavedEstimations] = useState<SavedEstimation[]>([]);
  const [isLoadingEstimations, setIsLoadingEstimations] = useState(false);
  const [selectedWeeks, setSelectedWeeks] = useState<Set<string>>(new Set());
  const [expandedWeeks, setExpandedWeeks] = useState<Set<string>>(new Set());
  
  const [form, setForm] = useState({
    pengepul_id: "",
    tanggal_ambil: format(new Date(), "yyyy-MM-dd"),
    jumlah_kg: "",
    catatan: "",
    is_organic: true,
  });

  // Load saved estimations
  useEffect(() => {
    const loadEstimations = async () => {
      setIsLoadingEstimations(true);
      try {
        const { data, error } = await supabase
          .from("estimasi_panen")
          .select("*")
          .order("created_at", { ascending: false });

        if (error) throw error;
        setSavedEstimations(data as unknown as SavedEstimation[]);
      } catch (error) {
        console.error("Error loading estimations:", error);
      } finally {
        setIsLoadingEstimations(false);
      }
    };
    loadEstimations();
  }, []);

  // Process estimations into week-based structure for barang keluar
  const weeklyEstimationData = useMemo((): WeekData[] => {
    const today = startOfDay(new Date());
    const weeks: WeekData[] = [];

    savedEstimations.forEach(estimation => {
      const panenData = estimation.data_panen as unknown as Array<{
        weekIndex: number;
        startDate: string;
        endDate: string;
        farmersData: FarmerWeeklyData[];
        holidays: number[];
      }>;

      if (!panenData) return;

      panenData.forEach(week => {
        const weekEndDate = new Date(week.endDate);
        const pickupDate = addDays(weekEndDate, 1); // Hari ke-8

        // Only show weeks where pickup date has passed
        if (isAfter(pickupDate, today)) return;

        const farmersOrganic: FarmerWeekEntry[] = [];
        const farmersConventional: FarmerWeekEntry[] = [];

        week.farmersData.forEach(farmerData => {
          const farmer = farmers.find(f => f.id === farmerData.farmerId);
          if (!farmer || !farmer.pengepul_id) return;

          const pengepul = pengepulList.find(p => p.id === farmer.pengepul_id);
          if (!pengepul) return;

          const dailyValues = farmerData.dailySales.map(d => d.value);
          const total = dailyValues.reduce((sum, v) => sum + v, 0);
          const isOrganic = farmerData.isOrganic !== false;

          // Check if this farmer has penjualan data for this week
          const hasPenjualan = penjualanList.some(p => 
            p.petani_id === farmerData.farmerId &&
            p.catatan?.includes(estimation.nama_estimasi) &&
            p.catatan?.includes(week.weekIndex + 1 + '')
          );

          if (!hasPenjualan) return; // Only include if barang masuk exists

          const entry: FarmerWeekEntry = {
            farmerId: farmerData.farmerId,
            farmerName: farmerData.farmerName,
            farmerCode: farmerData.farmerCode,
            pengepulId: farmer.pengepul_id,
            pengepulName: pengepul.nama,
            dailyValues,
            total,
            isOrganic,
          };

          if (isOrganic) {
            farmersOrganic.push(entry);
          } else {
            farmersConventional.push(entry);
          }
        });

        // Check if this week already has pengambilan entries
        const isProcessed = pengambilanList.some(p => 
          p.catatan?.includes(estimation.nama_estimasi) &&
          p.catatan?.includes(`Minggu ${week.weekIndex + 1}`)
        );

        if (farmersOrganic.length === 0 && farmersConventional.length === 0) return;

        weeks.push({
          estimationId: estimation.id,
          estimationName: estimation.nama_estimasi,
          weekIndex: week.weekIndex,
          weekLabel: `Minggu ${week.weekIndex + 1}`,
          startDate: week.startDate,
          endDate: week.endDate,
          pickupDate: format(pickupDate, "yyyy-MM-dd"),
          farmersOrganic,
          farmersConventional,
          totalOrganic: farmersOrganic.reduce((sum, f) => sum + f.total, 0),
          totalConventional: farmersConventional.reduce((sum, f) => sum + f.total, 0),
          isProcessed,
        });
      });
    });

    return weeks.sort((a, b) => a.startDate.localeCompare(b.startDate));
  }, [savedEstimations, farmers, pengepulList, penjualanList, pengambilanList]);

  const unprocessedWeeks = weeklyEstimationData.filter(w => !w.isProcessed);

  const resetForm = () => {
    setForm({
      pengepul_id: "",
      tanggal_ambil: format(new Date(), "yyyy-MM-dd"),
      jumlah_kg: "",
      catatan: "",
      is_organic: true,
    });
  };

  const toggleLot = (lotKey: string) => {
    setExpandedLots(prev => {
      const newSet = new Set(prev);
      if (newSet.has(lotKey)) {
        newSet.delete(lotKey);
      } else {
        newSet.add(lotKey);
      }
      return newSet;
    });
  };

  const toggleWeek = (weekKey: string) => {
    setExpandedWeeks(prev => {
      const newSet = new Set(prev);
      if (newSet.has(weekKey)) {
        newSet.delete(weekKey);
      } else {
        newSet.add(weekKey);
      }
      return newSet;
    });
  };

  const handleToggleWeekSelection = (weekKey: string) => {
    setSelectedWeeks(prev => {
      const newSet = new Set(prev);
      if (newSet.has(weekKey)) {
        newSet.delete(weekKey);
      } else {
        newSet.add(weekKey);
      }
      return newSet;
    });
  };

  const handleSelectAllWeeks = () => {
    if (selectedWeeks.size === unprocessedWeeks.length) {
      setSelectedWeeks(new Set());
    } else {
      setSelectedWeeks(new Set(unprocessedWeeks.map(w => `${w.estimationId}-${w.weekIndex}`)));
    }
  };

  const handleAutoGenerate = async () => {
    if (selectedWeeks.size === 0) {
      toast({
        title: "Pilih Minggu",
        description: "Pilih minimal satu minggu untuk diproses",
        variant: "destructive",
      });
      return;
    }

    setGeneratingAuto(true);
    let successCount = 0;

    for (const weekKey of selectedWeeks) {
      const week = weeklyEstimationData.find(w => `${w.estimationId}-${w.weekIndex}` === weekKey);
      if (!week) continue;

      // Group by pengepul and organic status
      const pengepulGroups = new Map<string, {
        pengepulId: string;
        isOrganic: boolean;
        totalKg: number;
        farmers: { id: string; name: string; code: string; kg: number }[];
      }>();

      const allFarmers = [...week.farmersOrganic, ...week.farmersConventional];

      allFarmers.forEach(farmer => {
        const key = `${farmer.pengepulId}-${farmer.isOrganic ? 'organic' : 'conventional'}`;
        
        if (!pengepulGroups.has(key)) {
          pengepulGroups.set(key, {
            pengepulId: farmer.pengepulId,
            isOrganic: farmer.isOrganic,
            totalKg: 0,
            farmers: [],
          });
        }

        const group = pengepulGroups.get(key)!;
        group.totalKg += farmer.total;
        group.farmers.push({
          id: farmer.farmerId,
          name: farmer.farmerName,
          code: farmer.farmerCode,
          kg: farmer.total,
        });
      });

      // Create pengambilan for each pengepul group
      for (const [, group] of pengepulGroups) {
        await addPengambilan({
          pengepul_id: group.pengepulId,
          tanggal_ambil: week.pickupDate,
          jumlah_kg: Math.round(group.totalKg * 10) / 10,
          batch_id: null,
          catatan: `Auto-generated dari estimasi: ${week.estimationName} - ${week.weekLabel} (${group.isOrganic ? 'Organik' : 'Konvensional'})`,
          is_organic: group.isOrganic,
          lot_number: `LOT-${format(new Date(week.pickupDate), "yyyyMMdd")}-${group.isOrganic ? 'ORG' : 'CNV'}`,
          detail_petani: group.farmers.map(f => ({
            petani_id: f.id,
            petani_nama: f.name,
            petani_kode: f.code,
            jumlah_kg: f.kg,
          })),
        } as any);
        successCount++;
      }
    }

    setGeneratingAuto(false);
    setSelectedWeeks(new Set());
    setAutoGenerateDialogOpen(false);
    refetch();

    toast({
      title: "Berhasil",
      description: `${successCount} data barang keluar berhasil ditambahkan`,
    });
  };

  const handleSubmit = async () => {
    if (!form.pengepul_id || !form.jumlah_kg) return;

    await addPengambilan({
      pengepul_id: form.pengepul_id,
      tanggal_ambil: form.tanggal_ambil,
      jumlah_kg: parseFloat(form.jumlah_kg),
      batch_id: null,
      catatan: form.catatan || null,
      lot_number: null,
      is_organic: form.is_organic,
      detail_petani: null,
    });

    resetForm();
    setDialogOpen(false);
  };

  const handleDelete = async (id: string) => {
    if (confirm("Yakin ingin menghapus data ini?")) {
      await deletePengambilan(id);
    }
  };

  // Group display data by week and organic status
  const displayLots = useMemo((): { organic: DisplayLot[]; conventional: DisplayLot[] } => {
    const organicLots: DisplayLot[] = [];
    const conventionalLots: DisplayLot[] = [];

    // Group by estimation-week-organic
    const groupMap = new Map<string, DisplayLot>();

    const filtered = filterPengepul === "all" 
      ? pengambilanList 
      : pengambilanList.filter(p => p.pengepul_id === filterPengepul);

    filtered.forEach(item => {
      const match = item.catatan?.match(/Auto-generated dari estimasi: (.+?) - (Minggu \d+) \((Organik|Konvensional)\)/);
      if (match) {
        const [, estName, weekLabel, type] = match;
        const isOrganic = type === 'Organik';
        const key = `${estName}-${weekLabel}-${type}`;

        if (!groupMap.has(key)) {
          groupMap.set(key, {
            lotKey: key,
            estimationName: estName,
            weekLabel,
            startDate: '',
            endDate: '',
            isOrganic,
            farmers: [],
            totalKg: 0,
            items: [],
          });
        }

        const lot = groupMap.get(key)!;
        lot.totalKg += Number(item.jumlah_kg);
        lot.items.push({
          id: item.id,
          pengepul_nama: item.pengepul?.nama || 'Unknown',
          jumlah_kg: Number(item.jumlah_kg),
        });

        // Parse farmer details
        const detailPetani = (item as any).detail_petani;
        if (Array.isArray(detailPetani)) {
          detailPetani.forEach((f: any) => {
            const existingFarmer = lot.farmers.find(x => x.petani_id === f.petani_id);
            if (!existingFarmer) {
              lot.farmers.push({
                petani_id: f.petani_id || f.id,
                petani_nama: f.petani_nama || f.name,
                petani_kode: f.petani_kode || f.code,
                jumlah_kg: f.jumlah_kg || f.kg,
              });
            }
          });
        }
      }
    });

    groupMap.forEach(lot => {
      if (lot.isOrganic) {
        organicLots.push(lot);
      } else {
        conventionalLots.push(lot);
      }
    });

    return { organic: organicLots, conventional: conventionalLots };
  }, [pengambilanList, filterPengepul]);

  const renderLotCard = (lot: DisplayLot) => {
    const isExpanded = expandedLots.has(lot.lotKey);

    return (
      <Collapsible key={lot.lotKey} open={isExpanded} onOpenChange={() => toggleLot(lot.lotKey)}>
        <Card className={lot.isOrganic ? "border-green-200" : "border-orange-200"}>
          <CardHeader className="py-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <CollapsibleTrigger asChild>
                  <Button variant="ghost" size="icon" className="h-6 w-6">
                    {isExpanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
                  </Button>
                </CollapsibleTrigger>
                <div>
                  <p className="font-medium">{lot.estimationName} - {lot.weekLabel}</p>
                  <div className="flex items-center gap-2">
                    <Badge variant={lot.isOrganic ? "default" : "secondary"} className={lot.isOrganic ? "bg-green-600" : "bg-orange-500"}>
                      {lot.isOrganic ? "Organik" : "Konvensional"}
                    </Badge>
                    <span className="text-sm text-muted-foreground">{lot.farmers.length} petani</span>
                  </div>
                </div>
              </div>
              <Badge variant="outline" className="text-lg">
                {lot.totalKg.toLocaleString()} Kg
              </Badge>
            </div>
          </CardHeader>
          <CollapsibleContent>
            <CardContent className="pt-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Nama Petani</TableHead>
                    <TableHead>Kode</TableHead>
                    <TableHead className="text-right">Jumlah (Kg)</TableHead>
                    <TableHead className="text-right">Aksi</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {lot.farmers.map((farmer, idx) => (
                    <TableRow key={idx}>
                      <TableCell className="font-medium">{farmer.petani_nama}</TableCell>
                      <TableCell>{farmer.petani_kode}</TableCell>
                      <TableCell className="text-right">{farmer.jumlah_kg.toLocaleString()}</TableCell>
                      <TableCell className="text-right">
                        <Button 
                          variant="ghost" 
                          size="icon"
                          onClick={() => lot.items.forEach(item => handleDelete(item.id))}
                        >
                          <Trash2 className="h-4 w-4 text-destructive" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                  <TableRow className="bg-muted/50">
                    <TableCell colSpan={2} className="font-bold">Total</TableCell>
                    <TableCell className="text-right font-bold">{lot.totalKg.toLocaleString()} Kg</TableCell>
                    <TableCell></TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </CollapsibleContent>
        </Card>
      </Collapsible>
    );
  };

  if (loading) {
    return <TableSkeleton rows={5} columns={6} />;
  }

  return (
    <div className="space-y-6">
      {/* Header Card */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between flex-wrap gap-4">
          <div>
            <CardTitle className="flex items-center gap-2">
              <ArrowUpFromLine className="h-5 w-5" />
              Barang Keluar
            </CardTitle>
            <CardDescription>Pengambilan koperasi dari pengepul (hari ke-8)</CardDescription>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            <Select value={filterPengepul} onValueChange={setFilterPengepul}>
              <SelectTrigger className="w-48">
                <SelectValue placeholder="Filter Pengepul" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Semua Pengepul</SelectItem>
                {pengepulList.map((p) => (
                  <SelectItem key={p.id} value={p.id}>{p.nama}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            
            {/* Auto Generate Dialog */}
            <Dialog open={autoGenerateDialogOpen} onOpenChange={(open) => {
              setAutoGenerateDialogOpen(open);
              if (!open) {
                setSelectedWeeks(new Set());
              }
            }}>
              <DialogTrigger asChild>
                <Button variant="outline" className="border-primary text-primary hover:bg-primary/10">
                  <Wand2 className="h-4 w-4 mr-2" />
                  Auto Generate
                  {unprocessedWeeks.length > 0 && (
                    <span className="ml-2 bg-primary text-primary-foreground px-2 py-0.5 rounded-full text-xs">
                      {unprocessedWeeks.length} minggu
                    </span>
                  )}
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-5xl max-h-[85vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle className="flex items-center gap-2">
                    <Wand2 className="h-5 w-5 text-primary" />
                    Auto Generate Barang Keluar
                  </DialogTitle>
                  <DialogDescription>
                    Buat data pengambilan koperasi dari barang masuk yang sudah tersedia (hari ke-8).
                  </DialogDescription>
                </DialogHeader>

                {isLoadingEstimations ? (
                  <div className="text-center py-8">
                    <p className="text-muted-foreground">Memuat data...</p>
                  </div>
                ) : unprocessedWeeks.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    <Check className="h-12 w-12 mx-auto mb-3 text-green-500" />
                    <p className="font-medium">Semua minggu sudah diproses</p>
                    <p className="text-sm">Tidak ada data baru. Pastikan Barang Masuk sudah di-generate terlebih dahulu.</p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {/* Select All */}
                    <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                      <div className="flex items-center gap-2">
                        <Checkbox
                          checked={selectedWeeks.size === unprocessedWeeks.length}
                          onCheckedChange={handleSelectAllWeeks}
                        />
                        <span className="font-medium">Pilih Semua Minggu ({unprocessedWeeks.length})</span>
                      </div>
                      <Button 
                        onClick={handleAutoGenerate} 
                        disabled={selectedWeeks.size === 0 || generatingAuto}
                      >
                        {generatingAuto ? "Memproses..." : `Generate ${selectedWeeks.size} Minggu`}
                      </Button>
                    </div>

                    {/* Week Cards */}
                    {unprocessedWeeks.map(week => {
                      const weekKey = `${week.estimationId}-${week.weekIndex}`;
                      const isExpanded = expandedWeeks.has(weekKey);
                      const isSelected = selectedWeeks.has(weekKey);

                      return (
                        <Collapsible key={weekKey} open={isExpanded} onOpenChange={() => toggleWeek(weekKey)}>
                          <Card className={isSelected ? "border-primary" : ""}>
                            <CardHeader className="py-3">
                              <div className="flex items-center justify-between">
                                <div className="flex items-center gap-3">
                                  <Checkbox
                                    checked={isSelected}
                                    onCheckedChange={() => handleToggleWeekSelection(weekKey)}
                                  />
                                  <CollapsibleTrigger asChild>
                                    <Button variant="ghost" size="icon" className="h-6 w-6">
                                      {isExpanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
                                    </Button>
                                  </CollapsibleTrigger>
                                  <div>
                                    <p className="font-medium">{week.estimationName} - {week.weekLabel}</p>
                                    <p className="text-sm text-muted-foreground flex items-center gap-1">
                                      <Calendar className="h-3 w-3" />
                                      Pengambilan: {format(new Date(week.pickupDate), "dd MMM yyyy", { locale: localeId })}
                                    </p>
                                  </div>
                                </div>
                                <div className="flex items-center gap-4">
                                  <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                                    <Leaf className="h-3 w-3 mr-1" />
                                    {week.totalOrganic.toLocaleString()} Kg
                                  </Badge>
                                  <Badge variant="outline" className="bg-orange-50 text-orange-700 border-orange-200">
                                    <Factory className="h-3 w-3 mr-1" />
                                    {week.totalConventional.toLocaleString()} Kg
                                  </Badge>
                                </div>
                              </div>
                            </CardHeader>
                            <CollapsibleContent>
                              <CardContent className="pt-0">
                                <div className="grid grid-cols-2 gap-6">
                                  {/* Organic Table */}
                                  {week.farmersOrganic.length > 0 && (
                                    <div className="space-y-2">
                                      <div className="flex items-center gap-2 text-sm font-medium text-green-700">
                                        <Leaf className="h-4 w-4" />
                                        Produk Organik ({week.farmersOrganic.length} petani)
                                      </div>
                                      <Table>
                                        <TableHeader>
                                          <TableRow>
                                            <TableHead>Nama Petani</TableHead>
                                            <TableHead>Kode</TableHead>
                                            <TableHead className="text-right">Total (Kg)</TableHead>
                                          </TableRow>
                                        </TableHeader>
                                        <TableBody>
                                          {week.farmersOrganic.map(farmer => (
                                            <TableRow key={farmer.farmerId}>
                                              <TableCell className="font-medium">{farmer.farmerName}</TableCell>
                                              <TableCell>{farmer.farmerCode}</TableCell>
                                              <TableCell className="text-right font-bold">{farmer.total.toLocaleString()}</TableCell>
                                            </TableRow>
                                          ))}
                                        </TableBody>
                                      </Table>
                                    </div>
                                  )}

                                  {/* Conventional Table */}
                                  {week.farmersConventional.length > 0 && (
                                    <div className="space-y-2">
                                      <div className="flex items-center gap-2 text-sm font-medium text-orange-700">
                                        <Factory className="h-4 w-4" />
                                        Produk Konvensional ({week.farmersConventional.length} petani)
                                      </div>
                                      <Table>
                                        <TableHeader>
                                          <TableRow>
                                            <TableHead>Nama Petani</TableHead>
                                            <TableHead>Kode</TableHead>
                                            <TableHead className="text-right">Total (Kg)</TableHead>
                                          </TableRow>
                                        </TableHeader>
                                        <TableBody>
                                          {week.farmersConventional.map(farmer => (
                                            <TableRow key={farmer.farmerId}>
                                              <TableCell className="font-medium">{farmer.farmerName}</TableCell>
                                              <TableCell>{farmer.farmerCode}</TableCell>
                                              <TableCell className="text-right font-bold">{farmer.total.toLocaleString()}</TableCell>
                                            </TableRow>
                                          ))}
                                        </TableBody>
                                      </Table>
                                    </div>
                                  )}
                                </div>
                              </CardContent>
                            </CollapsibleContent>
                          </Card>
                        </Collapsible>
                      );
                    })}
                  </div>
                )}
              </DialogContent>
            </Dialog>

            <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
              <DialogTrigger asChild>
                <Button className="bg-gradient-organic">
                  <Plus className="h-4 w-4 mr-2" />
                  Tambah Manual
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Tambah Barang Keluar Manual</DialogTitle>
                  <DialogDescription>Input pengambilan koperasi secara manual</DialogDescription>
                </DialogHeader>
                <div className="space-y-4">
                  <div>
                    <Label>Pengepul *</Label>
                    <Select value={form.pengepul_id} onValueChange={v => setForm(prev => ({ ...prev, pengepul_id: v }))}>
                      <SelectTrigger><SelectValue placeholder="Pilih pengepul" /></SelectTrigger>
                      <SelectContent>
                        {pengepulList.map(p => (
                          <SelectItem key={p.id} value={p.id}>{p.nama}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label>Tanggal Ambil</Label>
                      <Input type="date" value={form.tanggal_ambil} onChange={e => setForm(prev => ({ ...prev, tanggal_ambil: e.target.value }))} />
                    </div>
                    <div>
                      <Label>Jumlah (Kg) *</Label>
                      <Input type="number" value={form.jumlah_kg} onChange={e => setForm(prev => ({ ...prev, jumlah_kg: e.target.value }))} />
                    </div>
                  </div>
                  <div>
                    <Label>Tipe Produk</Label>
                    <Select value={form.is_organic ? "organic" : "conventional"} onValueChange={v => setForm(prev => ({ ...prev, is_organic: v === "organic" }))}>
                      <SelectTrigger><SelectValue /></SelectTrigger>
                      <SelectContent>
                        <SelectItem value="organic">Organik</SelectItem>
                        <SelectItem value="conventional">Konvensional</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label>Catatan</Label>
                    <Textarea value={form.catatan} onChange={e => setForm(prev => ({ ...prev, catatan: e.target.value }))} />
                  </div>
                  <Button onClick={handleSubmit} className="w-full">Simpan</Button>
                </div>
              </DialogContent>
            </Dialog>
          </div>
        </CardHeader>
      </Card>

      {/* Display Data */}
      {pengambilanList.length === 0 ? (
        <Card className="p-8 text-center text-muted-foreground">
          <ArrowUpFromLine className="h-12 w-12 mx-auto mb-3 opacity-50" />
          <p className="font-medium">Belum ada data barang keluar</p>
          <p className="text-sm">Gunakan Auto Generate setelah Barang Masuk tersedia</p>
        </Card>
      ) : (
        <div className="grid grid-cols-2 gap-6">
          {/* Organic Column */}
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-lg font-semibold text-green-700">
              <Leaf className="h-5 w-5" />
              Produk Organik
              <Badge variant="outline" className="bg-green-50">
                {displayLots.organic.length} lot
              </Badge>
            </div>
            {displayLots.organic.length === 0 ? (
              <Card className="p-4 text-center text-muted-foreground">
                <p className="text-sm">Belum ada data organik</p>
              </Card>
            ) : (
              displayLots.organic.map(lot => renderLotCard(lot))
            )}
          </div>

          {/* Conventional Column */}
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-lg font-semibold text-orange-700">
              <Factory className="h-5 w-5" />
              Produk Konvensional
              <Badge variant="outline" className="bg-orange-50">
                {displayLots.conventional.length} lot
              </Badge>
            </div>
            {displayLots.conventional.length === 0 ? (
              <Card className="p-4 text-center text-muted-foreground">
                <p className="text-sm">Belum ada data konvensional</p>
              </Card>
            ) : (
              displayLots.conventional.map(lot => renderLotCard(lot))
            )}
          </div>
        </div>
      )}
    </div>
  );
};
