import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Plus, ArrowUpFromLine, Trash2, Wand2, AlertCircle } from "lucide-react";
import { usePengambilanKoperasi } from "@/hooks/use-pengambilan-koperasi";
import { usePenjualanPetani } from "@/hooks/use-penjualan-petani";
import { usePengepul } from "@/hooks/use-pengepul";
import { TableSkeleton } from "@/components/ui/skeleton-templates";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { format, subDays, addDays, isBefore, isAfter, startOfDay } from "date-fns";
import { id as localeId } from "date-fns/locale";
import { toast } from "@/hooks/use-toast";

interface AutoGenerateResult {
  pengepul_id: string;
  pengepul_nama: string;
  pengepul_kode: string;
  tanggal_ambil: string;
  jumlah_kg: number;
  source_dates: string[];
}

export const BarangKeluarTab = () => {
  const { pengambilanList, loading, addPengambilan, deletePengambilan, refetch } = usePengambilanKoperasi();
  const { penjualanList, loading: penjualanLoading } = usePenjualanPetani();
  const { pengepulList } = usePengepul();
  
  const [dialogOpen, setDialogOpen] = useState(false);
  const [autoGenerateDialogOpen, setAutoGenerateDialogOpen] = useState(false);
  const [filterPengepul, setFilterPengepul] = useState<string>("all");
  const [autoGenerateResults, setAutoGenerateResults] = useState<AutoGenerateResult[]>([]);
  const [generatingAuto, setGeneratingAuto] = useState(false);
  
  const [form, setForm] = useState({
    pengepul_id: "",
    tanggal_ambil: format(new Date(), "yyyy-MM-dd"),
    jumlah_kg: "",
    catatan: "",
  });

  const resetForm = () => {
    setForm({
      pengepul_id: "",
      tanggal_ambil: format(new Date(), "yyyy-MM-dd"),
      jumlah_kg: "",
      catatan: "",
    });
  };

  // Auto-generate barang keluar berdasarkan hari ke-8 dari penjualan petani
  const generateAutoBarangKeluar = () => {
    const today = startOfDay(new Date());
    const results: AutoGenerateResult[] = [];
    
    // Group penjualan by pengepul and date
    const penjualanByPengepulDate = new Map<string, { pengepul: any; dates: Map<string, number> }>();
    
    for (const p of penjualanList) {
      const saleDate = startOfDay(new Date(p.tanggal_jual));
      const day8Date = addDays(saleDate, 7); // Hari ke-8 = 7 hari setelah penjualan
      
      // Only include if day8 is today or in the past
      if (isAfter(day8Date, today)) continue;
      
      const key = p.pengepul_id;
      const day8Str = format(day8Date, "yyyy-MM-dd");
      
      if (!penjualanByPengepulDate.has(key)) {
        penjualanByPengepulDate.set(key, {
          pengepul: p.pengepul,
          dates: new Map(),
        });
      }
      
      const pengepulData = penjualanByPengepulDate.get(key)!;
      const currentKg = pengepulData.dates.get(day8Str) || 0;
      pengepulData.dates.set(day8Str, currentKg + Number(p.jumlah_kg));
    }
    
    // Check which ones don't have existing pengambilan
    for (const [pengepulId, data] of penjualanByPengepulDate) {
      for (const [tanggalAmbil, jumlahKg] of data.dates) {
        // Check if pengambilan already exists for this pengepul and date
        const exists = pengambilanList.some(
          p => p.pengepul_id === pengepulId && p.tanggal_ambil === tanggalAmbil
        );
        
        if (!exists && jumlahKg > 0) {
          results.push({
            pengepul_id: pengepulId,
            pengepul_nama: data.pengepul?.nama || "Unknown",
            pengepul_kode: data.pengepul?.kode_pengepul || "-",
            tanggal_ambil: tanggalAmbil,
            jumlah_kg: jumlahKg,
            source_dates: [],
          });
        }
      }
    }
    
    // Sort by date
    results.sort((a, b) => a.tanggal_ambil.localeCompare(b.tanggal_ambil));
    
    return results;
  };

  const handleAutoGenerate = () => {
    const results = generateAutoBarangKeluar();
    setAutoGenerateResults(results);
    setAutoGenerateDialogOpen(true);
  };

  const handleConfirmAutoGenerate = async () => {
    setGeneratingAuto(true);
    try {
      for (const result of autoGenerateResults) {
        await addPengambilan({
          pengepul_id: result.pengepul_id,
          tanggal_ambil: result.tanggal_ambil,
          jumlah_kg: result.jumlah_kg,
          batch_id: null,
          catatan: `Auto-generated dari penjualan petani (hari ke-8)`,
        });
      }
      
      toast({
        title: "Berhasil",
        description: `${autoGenerateResults.length} data barang keluar berhasil ditambahkan`,
      });
      
      setAutoGenerateDialogOpen(false);
      setAutoGenerateResults([]);
      refetch();
    } catch (error) {
      console.error("Error auto-generating:", error);
      toast({
        title: "Error",
        description: "Gagal menambahkan data barang keluar",
        variant: "destructive",
      });
    } finally {
      setGeneratingAuto(false);
    }
  };

  const handleSubmit = async () => {
    if (!form.pengepul_id || !form.jumlah_kg) return;

    await addPengambilan({
      pengepul_id: form.pengepul_id,
      tanggal_ambil: form.tanggal_ambil,
      jumlah_kg: parseFloat(form.jumlah_kg),
      batch_id: null,
      catatan: form.catatan || null,
    });

    resetForm();
    setDialogOpen(false);
  };

  const handleDelete = async (id: string) => {
    if (confirm("Yakin ingin menghapus data ini?")) {
      await deletePengambilan(id);
    }
  };

  // Filter list by pengepul
  const filteredList = filterPengepul === "all" 
    ? pengambilanList 
    : pengambilanList.filter(p => p.pengepul_id === filterPengepul);

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="flex items-center gap-2">
            <ArrowUpFromLine className="h-5 w-5" />
            Barang Keluar
          </CardTitle>
          <CardDescription>Pengambilan oleh koperasi (hari ke-8 dari penjualan petani)</CardDescription>
        </div>
        <div className="flex flex-wrap items-center gap-2 sm:gap-4">
          <Select value={filterPengepul} onValueChange={setFilterPengepul}>
            <SelectTrigger className="w-40 sm:w-48">
              <SelectValue placeholder="Filter Pengepul" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Semua Pengepul</SelectItem>
              {pengepulList.map((p) => (
                <SelectItem key={p.id} value={p.id}>{p.nama}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          
          {/* Auto Generate Button */}
          <Button 
            variant="outline" 
            onClick={handleAutoGenerate}
            disabled={penjualanLoading}
          >
            <Wand2 className="h-4 w-4 mr-2" />
            Auto Generate
          </Button>
          
          <Dialog open={dialogOpen} onOpenChange={(open) => {
            setDialogOpen(open);
            if (!open) resetForm();
          }}>
            <DialogTrigger asChild>
              <Button className="bg-gradient-organic">
                <Plus className="h-4 w-4 mr-2" />
                Tambah Manual
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Tambah Barang Keluar</DialogTitle>
                <DialogDescription>Catat pengambilan barang oleh koperasi</DialogDescription>
              </DialogHeader>
              <div className="grid gap-4 py-4">
                <div>
                  <Label>Pengepul *</Label>
                  <Select 
                    value={form.pengepul_id} 
                    onValueChange={(value) => setForm(prev => ({ ...prev, pengepul_id: value }))}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Pilih pengepul" />
                    </SelectTrigger>
                    <SelectContent>
                      {pengepulList.map((p) => (
                        <SelectItem key={p.id} value={p.id}>
                          {p.kode_pengepul} - {p.nama}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label>Tanggal Pengambilan *</Label>
                  <Input
                    type="date"
                    value={form.tanggal_ambil}
                    onChange={(e) => setForm(prev => ({ ...prev, tanggal_ambil: e.target.value }))}
                  />
                </div>
                <div>
                  <Label>Jumlah (Kg) *</Label>
                  <Input
                    type="number"
                    step="0.1"
                    value={form.jumlah_kg}
                    onChange={(e) => setForm(prev => ({ ...prev, jumlah_kg: e.target.value }))}
                    placeholder="0"
                  />
                </div>
                <div>
                  <Label>Catatan</Label>
                  <Textarea
                    value={form.catatan}
                    onChange={(e) => setForm(prev => ({ ...prev, catatan: e.target.value }))}
                    placeholder="Catatan tambahan..."
                  />
                </div>
                <div className="flex justify-end gap-2">
                  <Button variant="outline" onClick={() => { setDialogOpen(false); resetForm(); }}>Batal</Button>
                  <Button onClick={handleSubmit} className="bg-gradient-organic">Simpan</Button>
                </div>
              </div>
            </DialogContent>
          </Dialog>
        </div>
      </CardHeader>
      <CardContent>
        {loading ? (
          <TableSkeleton rows={5} columns={5} />
        ) : filteredList.length === 0 ? (
          <div className="text-center py-8 text-muted-foreground">
            <ArrowUpFromLine className="h-12 w-12 mx-auto mb-3 opacity-50" />
            <p>Belum ada data barang keluar</p>
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Tanggal</TableHead>
                <TableHead>Pengepul</TableHead>
                <TableHead>Jumlah (Kg)</TableHead>
                <TableHead>Status Batch</TableHead>
                <TableHead>Catatan</TableHead>
                <TableHead className="text-right">Aksi</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredList.map((item) => (
                <TableRow key={item.id}>
                  <TableCell>
                    {format(new Date(item.tanggal_ambil), "dd MMM yyyy", { locale: localeId })}
                  </TableCell>
                  <TableCell>
                    <div>
                      <p className="font-medium">{item.pengepul?.nama}</p>
                      <p className="text-xs text-muted-foreground">{item.pengepul?.kode_pengepul}</p>
                    </div>
                  </TableCell>
                  <TableCell className="font-medium">{Number(item.jumlah_kg).toLocaleString()} Kg</TableCell>
                  <TableCell>
                    {item.batch_id ? (
                      <Badge variant="default">Sudah Diproses</Badge>
                    ) : (
                      <Badge variant="secondary">Belum Diproses</Badge>
                    )}
                  </TableCell>
                  <TableCell className="max-w-xs truncate">{item.catatan || "-"}</TableCell>
                  <TableCell className="text-right">
                    <Button 
                      variant="ghost" 
                      size="icon" 
                      onClick={() => handleDelete(item.id)}
                      disabled={!!item.batch_id}
                    >
                      <Trash2 className="h-4 w-4 text-destructive" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </CardContent>
      
      {/* Auto Generate Dialog */}
      <Dialog open={autoGenerateDialogOpen} onOpenChange={setAutoGenerateDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Wand2 className="h-5 w-5" />
              Auto Generate Barang Keluar
            </DialogTitle>
            <DialogDescription>
              Data berikut akan dibuat berdasarkan penjualan petani yang sudah melewati hari ke-8
            </DialogDescription>
          </DialogHeader>
          
          {autoGenerateResults.length === 0 ? (
            <Alert>
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>
                Tidak ada data barang keluar yang perlu di-generate. Semua penjualan petani yang sudah melewati hari ke-8 telah memiliki data pengambilan.
              </AlertDescription>
            </Alert>
          ) : (
            <div className="space-y-4">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Tanggal Pengambilan</TableHead>
                    <TableHead>Pengepul</TableHead>
                    <TableHead>Jumlah (Kg)</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {autoGenerateResults.map((result, idx) => (
                    <TableRow key={`${result.pengepul_id}-${result.tanggal_ambil}-${idx}`}>
                      <TableCell>
                        {format(new Date(result.tanggal_ambil), "dd MMM yyyy", { locale: localeId })}
                      </TableCell>
                      <TableCell>
                        <div>
                          <p className="font-medium">{result.pengepul_nama}</p>
                          <p className="text-xs text-muted-foreground">{result.pengepul_kode}</p>
                        </div>
                      </TableCell>
                      <TableCell className="font-medium">{result.jumlah_kg.toLocaleString()} Kg</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
              
              <div className="p-3 bg-primary/5 rounded-md">
                <p className="text-sm">
                  Total: <strong>{autoGenerateResults.length}</strong> data akan ditambahkan dengan total{" "}
                  <strong>{autoGenerateResults.reduce((sum, r) => sum + r.jumlah_kg, 0).toLocaleString()} Kg</strong>
                </p>
              </div>
            </div>
          )}
          
          <div className="flex justify-end gap-2 pt-4">
            <Button variant="outline" onClick={() => setAutoGenerateDialogOpen(false)}>
              Batal
            </Button>
            {autoGenerateResults.length > 0 && (
              <Button 
                onClick={handleConfirmAutoGenerate} 
                className="bg-gradient-organic"
                disabled={generatingAuto}
              >
                {generatingAuto ? "Memproses..." : "Generate Semua"}
              </Button>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </Card>
  );
};
