import { useState, useEffect, useMemo } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Progress } from "@/components/ui/progress";
import { Plus, ArrowDownToLine, Trash2, Sparkles, Check, FileText, Leaf, Factory, ChevronDown, ChevronRight, Calendar, Loader2 } from "lucide-react";
import { usePenjualanPetani, PenjualanPetani } from "@/hooks/use-penjualan-petani";
import { usePengepul } from "@/hooks/use-pengepul";
import { useFarmers } from "@/hooks/use-farmers";
import { TableSkeleton } from "@/components/ui/skeleton-templates";
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { format, addDays } from "date-fns";
import { id as localeId } from "date-fns/locale";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { SavedEstimation, FarmerWeeklyData, DailyData } from "@/hooks/use-harvest-estimation";

interface WeekData {
  estimationId: string;
  estimationName: string;
  weekIndex: number;
  weekLabel: string;
  startDate: string;
  endDate: string;
  farmersOrganic: FarmerWeekEntry[];
  farmersConventional: FarmerWeekEntry[];
  totalOrganic: number;
  totalConventional: number;
  isProcessed: boolean;
}

interface FarmerWeekEntry {
  farmerId: string;
  farmerName: string;
  farmerCode: string;
  pengepulId: string;
  pengepulName: string;
  dailyValues: number[];
  dailyDates: string[];
  total: number;
  isOrganic: boolean;
}

interface EstimationGroup {
  estimationName: string;
  estimationId: string;
  weeks: WeekData[];
  count: number;
  totalKg: number;
  ids: string[];
}

export const BarangMasukTab = () => {
  const { loading, addPenjualan, addPenjualanBatch, deletePenjualan, deletePenjualanBatch, refetch, fetchPenjualanByCatatan, totalCount } = usePenjualanPetani();
  const { pengepulList } = usePengepul();
  const { farmers } = useFarmers();
  
  const [dialogOpen, setDialogOpen] = useState(false);
  const [autoGenerateDialogOpen, setAutoGenerateDialogOpen] = useState(false);
  const [filterPengepul, setFilterPengepul] = useState<string>("all");

  const DISPLAY_PAGE_SIZE = 4;
  const [displayPage, setDisplayPage] = useState(1);

  // Store displayed week data fetched on-demand
  const [displayedWeeksData, setDisplayedWeeksData] = useState<PenjualanPetani[]>([]);
  const [isLoadingDisplay, setIsLoadingDisplay] = useState(false);

  const [selectedWeeks, setSelectedWeeks] = useState<Set<string>>(new Set());
  const [autoGenerateLoading, setAutoGenerateLoading] = useState(false);
  const [generateProgress, setGenerateProgress] = useState({ current: 0, total: 0 });
  const [savedEstimations, setSavedEstimations] = useState<SavedEstimation[]>([]);
  const [isLoadingEstimations, setIsLoadingEstimations] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [deletingEstimation, setDeletingEstimation] = useState<EstimationGroup | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [expandedWeeks, setExpandedWeeks] = useState<Set<string>>(new Set());
  
  const [form, setForm] = useState({
    pengepul_id: "",
    petani_id: "",
    tanggal_jual: format(new Date(), "yyyy-MM-dd"),
    jumlah_kg: "",
    harga_per_kg: "",
    warna_produk: "",
    kualitas: "grade_a",
    catatan: "",
    is_organic: true,
  });

  useEffect(() => {
    setDisplayPage(1);
  }, [filterPengepul]);

  // Load saved estimations
  useEffect(() => {
    const loadEstimations = async () => {
      setIsLoadingEstimations(true);
      try {
        const { data, error } = await supabase
          .from("estimasi_panen")
          .select("*")
          .order("created_at", { ascending: false });

        if (error) throw error;
        setSavedEstimations(data as unknown as SavedEstimation[]);
      } catch (error) {
        console.error("Error loading estimations:", error);
      } finally {
        setIsLoadingEstimations(false);
      }
    };
    loadEstimations();
  }, []);

  const resetForm = () => {
    setForm({
      pengepul_id: "",
      petani_id: "",
      tanggal_jual: format(new Date(), "yyyy-MM-dd"),
      jumlah_kg: "",
      harga_per_kg: "",
      warna_produk: "",
      kualitas: "grade_a",
      catatan: "",
      is_organic: true,
    });
  };

  // Filter farmers by selected pengepul
  const filteredFarmers = farmers.filter(f => f.pengepul_id === form.pengepul_id);

  // Auto-fill harga when pengepul is selected
  const handlePengepulChange = (pengepulId: string) => {
    const pengepul = pengepulList.find(p => p.id === pengepulId);
    setForm(prev => ({
      ...prev,
      pengepul_id: pengepulId,
      petani_id: "",
      harga_per_kg: pengepul ? String(pengepul.harga_beli) : "",
    }));
  };

  const handleSubmit = async () => {
    if (!form.pengepul_id || !form.petani_id || !form.jumlah_kg || !form.harga_per_kg) return;

    await addPenjualan({
      pengepul_id: form.pengepul_id,
      petani_id: form.petani_id,
      tanggal_jual: form.tanggal_jual,
      jumlah_kg: parseFloat(form.jumlah_kg),
      harga_per_kg: parseFloat(form.harga_per_kg),
      warna_produk: form.warna_produk || null,
      kualitas: form.kualitas,
      catatan: form.catatan || null,
      is_organic: form.is_organic,
    } as any);

    resetForm();
    setDialogOpen(false);
  };

  const handleDelete = async (id: string) => {
    if (confirm("Yakin ingin menghapus data ini?")) {
      await deletePenjualan(id);
    }
  };

  // Process estimations into week-based structure
  // Process estimations into week-based structure - use estimation data directly without strict filtering
  const weeklyEstimationData = useMemo((): WeekData[] => {
    const weeks: WeekData[] = [];

    savedEstimations.forEach(estimation => {
      const panenData = estimation.data_panen as unknown as Array<{
        weekIndex: number;
        startDate: string;
        endDate: string;
        farmersData: FarmerWeeklyData[];
        holidays: number[];
      }>;

      if (!panenData || !Array.isArray(panenData)) return;

      panenData.forEach(week => {
        if (!week.farmersData || !Array.isArray(week.farmersData)) return;

        const farmersOrganic: FarmerWeekEntry[] = [];
        const farmersConventional: FarmerWeekEntry[] = [];

        week.farmersData.forEach(farmerData => {
          if (!farmerData.dailySales || !Array.isArray(farmerData.dailySales)) return;

          // Get farmer info - use estimation data as primary, lookup as fallback
          const farmer = farmers.find(f => f.id === farmerData.farmerId);
          const pengepulId = farmer?.pengepul_id || '';
          const pengepul = pengepulId ? pengepulList.find(p => p.id === pengepulId) : null;

          const dailyValues = farmerData.dailySales.map(d => d.value || 0);
          const dailyDates = farmerData.dailySales.map(d => d.date);
          const total = dailyValues.reduce((sum, v) => sum + v, 0);
          const isOrganic = farmerData.isOrganic !== false;

          // Only skip if no valid sales data at all
          if (total === 0) return;

          const entry: FarmerWeekEntry = {
            farmerId: farmerData.farmerId,
            farmerName: farmerData.farmerName || farmer?.nama || 'Unknown',
            farmerCode: farmerData.farmerCode || farmer?.kode_petani || '-',
            pengepulId: pengepulId,
            pengepulName: pengepul?.nama || 'Tidak Ada Pengepul',
            dailyValues,
            dailyDates,
            total,
            isOrganic,
          };

          if (isOrganic) {
            farmersOrganic.push(entry);
          } else {
            farmersConventional.push(entry);
          }
        });

        // NOTE: status processed dihitung via query count (lihat weekProgressMap)
        const isProcessed = false;

        // Only add weeks that have at least one farmer with data
        if (farmersOrganic.length > 0 || farmersConventional.length > 0) {
          weeks.push({
            estimationId: estimation.id,
            estimationName: estimation.nama_estimasi,
            weekIndex: week.weekIndex,
            weekLabel: `Minggu ${week.weekIndex + 1}`,
            startDate: week.startDate,
            endDate: week.endDate,
            farmersOrganic,
            farmersConventional,
            totalOrganic: farmersOrganic.reduce((sum, f) => sum + f.total, 0),
            totalConventional: farmersConventional.reduce((sum, f) => sum + f.total, 0),
            isProcessed,
          });
        }
      });
    });

    return weeks.sort((a, b) => a.startDate.localeCompare(b.startDate));
  }, [savedEstimations, farmers, pengepulList]);
  const [weekProgressMap, setWeekProgressMap] = useState<Record<string, { expected: number; actual: number }>>({});
  const [weekProgressLoading, setWeekProgressLoading] = useState(false);

  const getWeekKey = (w: Pick<WeekData, "estimationId" | "weekIndex">) => `${w.estimationId}-${w.weekIndex}`;
  const getWeekCatatan = (w: Pick<WeekData, "estimationName" | "weekLabel">) =>
    `Auto-generated dari estimasi: ${w.estimationName} - ${w.weekLabel}`;

  const getExpectedEntries = (week: WeekData) => {
    const allFarmers = [...week.farmersOrganic, ...week.farmersConventional];
    let expected = 0;

    for (const farmer of allFarmers) {
      // Tidak bisa digenerate jika tidak ada pengepul
      if (!farmer.pengepulId) continue;
      for (const v of farmer.dailyValues) {
        if (v > 0) expected++;
      }
    }

    return expected;
  };

  const refreshWeekProgress = async () => {
    if (weeklyEstimationData.length === 0) return;

    setWeekProgressLoading(true);
    try {
      const results = await Promise.all(
        weeklyEstimationData.map(async (week) => {
          const expected = getExpectedEntries(week);
          if (expected === 0) return { key: getWeekKey(week), expected: 0, actual: 0 };

          const { count, error } = await supabase
            .from("penjualan_petani")
            .select("id", { count: "exact", head: true })
            .eq("catatan", getWeekCatatan(week));

          if (error) throw error;

          return { key: getWeekKey(week), expected, actual: count ?? 0 };
        }),
      );

      const next: Record<string, { expected: number; actual: number }> = {};
      results.forEach((r) => {
        next[r.key] = { expected: r.expected, actual: r.actual };
      });
      setWeekProgressMap(next);
    } catch (error) {
      console.error("Error checking week progress:", error);
    } finally {
      setWeekProgressLoading(false);
    }
  };

  useEffect(() => {
    refreshWeekProgress();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [weeklyEstimationData]);

  // Fetch display data based on processed weeks
  const loadDisplayData = async () => {
    if (weeklyEstimationData.length === 0) {
      setDisplayedWeeksData([]);
      return;
    }

    setIsLoadingDisplay(true);
    try {
      // Get catatan values for all weeks that have been processed
      const processedWeeks = weeklyEstimationData.filter((w) => {
        const key = getWeekKey(w);
        const actual = weekProgressMap[key]?.actual ?? 0;
        return actual > 0;
      });

      const catatanList = processedWeeks.map(getWeekCatatan);
      
      if (catatanList.length === 0) {
        setDisplayedWeeksData([]);
        return;
      }

      const data = await fetchPenjualanByCatatan(catatanList);
      setDisplayedWeeksData(data);
    } catch (error) {
      console.error("Error loading display data:", error);
    } finally {
      setIsLoadingDisplay(false);
    }
  };

  useEffect(() => {
    loadDisplayData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [weekProgressMap]);

  // Get unprocessed weeks (belum lengkap ter-generate)
  const unprocessedWeeks = useMemo(() => {
    return weeklyEstimationData.filter((w) => {
      const key = getWeekKey(w);
      const expected = weekProgressMap[key]?.expected ?? getExpectedEntries(w);
      const actual = weekProgressMap[key]?.actual ?? 0;
      return expected > 0 && actual < expected;
    });
  }, [weeklyEstimationData, weekProgressMap]);
  const toggleWeek = (weekKey: string) => {
    setExpandedWeeks(prev => {
      const newSet = new Set(prev);
      if (newSet.has(weekKey)) {
        newSet.delete(weekKey);
      } else {
        newSet.add(weekKey);
      }
      return newSet;
    });
  };

  const handleToggleWeekSelection = (weekKey: string) => {
    setSelectedWeeks(prev => {
      const newSet = new Set(prev);
      if (newSet.has(weekKey)) {
        newSet.delete(weekKey);
      } else {
        newSet.add(weekKey);
      }
      return newSet;
    });
  };

  const handleSelectAllWeeks = () => {
    if (selectedWeeks.size === unprocessedWeeks.length) {
      setSelectedWeeks(new Set());
    } else {
      setSelectedWeeks(new Set(unprocessedWeeks.map(w => `${w.estimationId}-${w.weekIndex}`)));
    }
  };

  const handleAutoGenerate = async () => {
    if (selectedWeeks.size === 0) {
      toast({
        title: "Pilih Minggu",
        description: "Pilih minimal satu minggu untuk diproses",
        variant: "destructive",
      });
      return;
    }

    setAutoGenerateLoading(true);
    setGenerateProgress({ current: 0, total: 0 });

    // Collect all data to insert first
    const dataToInsert: Array<{
      pengepul_id: string;
      petani_id: string;
      tanggal_jual: string;
      jumlah_kg: number;
      harga_per_kg: number;
      warna_produk: string | null;
      kualitas: string;
      catatan: string;
      is_organic: boolean;
    }> = [];

    const skippedFarmers: string[] = [];

    // Fetch existing entries untuk minggu-minggu yang dipilih langsung dari backend
    const selectedWeeksArray = Array.from(selectedWeeks);
    const selectedWeekObjects = selectedWeeksArray
      .map((weekKey) => weeklyEstimationData.find((w) => getWeekKey(w) === weekKey))
      .filter(Boolean) as WeekData[];

    const selectedCatatanList = selectedWeekObjects.map(getWeekCatatan);
    const existingKeySet = new Set<string>();

    if (selectedCatatanList.length > 0) {
      const { data: existing, error } = await supabase
        .from("penjualan_petani")
        .select("petani_id,tanggal_jual,is_organic,catatan")
        .in("catatan", selectedCatatanList)
        .limit(10000);

      if (error) {
        console.error("Error checking existing penjualan:", error);
      } else {
        (existing || []).forEach((row: any) => {
          existingKeySet.add(`${row.petani_id}|${row.tanggal_jual}|${row.is_organic !== false}`);
        });
      }
    }

    for (const weekKey of selectedWeeks) {
      const week = weeklyEstimationData.find(w => `${w.estimationId}-${w.weekIndex}` === weekKey);
      if (!week) continue;

      const allFarmers = [...week.farmersOrganic, ...week.farmersConventional];

      for (const farmerEntry of allFarmers) {
        // Try to find pengepul - if not in farmerEntry, try to find from farmer's pengepul_id
        let pengepulId = farmerEntry.pengepulId;
        let hargaBeli = 0;

        if (pengepulId) {
          const pengepul = pengepulList.find(p => p.id === pengepulId);
          if (pengepul) {
            hargaBeli = pengepul.harga_beli;
          }
        }

        // Skip if no pengepul_id - it's required for penjualan_petani
        if (!pengepulId) {
          if (!skippedFarmers.includes(farmerEntry.farmerName)) {
            skippedFarmers.push(farmerEntry.farmerName);
          }
          continue;
        }

        // Use default price if not found
        if (hargaBeli === 0) {
          hargaBeli = 10000; // Default price
        }

        // Create entry for each day with value > 0
        for (let i = 0; i < farmerEntry.dailyValues.length; i++) {
          const value = farmerEntry.dailyValues[i];
          const date = farmerEntry.dailyDates[i];
          
          if (value <= 0) continue;

          // Check if already exists (pakai data backend, bukan state penjualanList)
          const exists = existingKeySet.has(`${farmerEntry.farmerId}|${date}|${farmerEntry.isOrganic}`);
          if (exists) continue;

          dataToInsert.push({
            pengepul_id: pengepulId,
            petani_id: farmerEntry.farmerId,
            tanggal_jual: date,
            jumlah_kg: value,
            harga_per_kg: hargaBeli,
            warna_produk: null,
            kualitas: "grade_a",
            catatan: `Auto-generated dari estimasi: ${week.estimationName} - ${week.weekLabel}`,
            is_organic: farmerEntry.isOrganic,
          });
        }
      }
    }

    // Show warning if any farmers were skipped
    if (skippedFarmers.length > 0) {
      toast({
        title: "Peringatan",
        description: `${skippedFarmers.length} petani dilewati karena tidak memiliki pengepul: ${skippedFarmers.slice(0, 3).join(', ')}${skippedFarmers.length > 3 ? '...' : ''}`,
        variant: "destructive",
      });
    }

    if (dataToInsert.length === 0) {
      setAutoGenerateLoading(false);
      toast({
        title: "Tidak Ada Data",
        description: "Semua data sudah ada atau tidak ada data untuk diproses",
      });
      return;
    }

    setGenerateProgress({ current: 0, total: dataToInsert.length });

    // Use batch insert for better performance
    const result = await addPenjualanBatch(dataToInsert, (current, total) => {
      setGenerateProgress({ current, total });
    });

    setAutoGenerateLoading(false);
    setGenerateProgress({ current: 0, total: 0 });
    setSelectedWeeks(new Set());
    setAutoGenerateDialogOpen(false);
    
    // Refresh week progress which will trigger loadDisplayData
    refreshWeekProgress();

    if (result.success > 0) {
      toast({
        title: "Berhasil",
        description: `${result.success} data penjualan berhasil dibuat dari estimasi`,
      });
    }
    if (result.failed > 0) {
      toast({
        title: "Sebagian Gagal",
        description: `${result.failed} data gagal diproses`,
        variant: "destructive",
      });
    }
  };

  // Group processed entries by estimation - use displayedWeeksData
  const estimationGroups = useMemo((): EstimationGroup[] => {
    const groups: { [key: string]: EstimationGroup } = {};
    
    displayedWeeksData.forEach(item => {
      if (item.catatan && item.catatan.includes("Auto-generated dari estimasi:")) {
        const match = item.catatan.match(/Auto-generated dari estimasi: (.+?) - Minggu/);
        if (match) {
          const estimationName = match[1];
          if (!groups[estimationName]) {
            const estimation = savedEstimations.find(e => e.nama_estimasi === estimationName);
            groups[estimationName] = {
              estimationName,
              estimationId: estimation?.id || '',
              weeks: [],
              count: 0,
              totalKg: 0,
              ids: [],
            };
          }
          groups[estimationName].count++;
          groups[estimationName].totalKg += Number(item.jumlah_kg);
          groups[estimationName].ids.push(item.id);
        }
      }
    });

    return Object.values(groups).sort((a, b) => b.count - a.count);
  }, [displayedWeeksData, savedEstimations]);

  const handleDeleteEstimationGroup = async () => {
    if (!deletingEstimation) return;

    setIsDeleting(true);
    
    // Use batch delete for better performance
    const result = await deletePenjualanBatch(deletingEstimation.ids);

    setIsDeleting(false);
    setDeleteDialogOpen(false);
    setDeletingEstimation(null);
    
    // Refresh week progress and display data
    refreshWeekProgress();
    loadDisplayData();

    if (result.success > 0) {
      toast({
        title: "Berhasil Dihapus",
        description: `${result.success} data dari estimasi "${deletingEstimation.estimationName}" berhasil dihapus`,
      });
    }
    if (result.failed > 0) {
      toast({
        title: "Sebagian Gagal",
        description: `${result.failed} data gagal dihapus`,
        variant: "destructive",
      });
    }
  };

  // Filter and group display data by week - use displayedWeeksData
  const displayWeeks = useMemo(() => {
    const filtered = filterPengepul === "all" 
      ? displayedWeeksData 
      : displayedWeeksData.filter(p => p.pengepul_id === filterPengepul);

    // Group by week (based on catatan)
    const weekMap = new Map<string, {
      weekLabel: string;
      estimationName: string;
      organic: PenjualanPetani[];
      conventional: PenjualanPetani[];
    }>();

    filtered.forEach(item => {
      const match = item.catatan?.match(/Auto-generated dari estimasi: (.+?) - (Minggu \d+)/);
      if (match) {
        const [, estName, weekLabel] = match;
        const key = `${estName}-${weekLabel}`;
        
        if (!weekMap.has(key)) {
          weekMap.set(key, {
            weekLabel,
            estimationName: estName,
            organic: [],
            conventional: [],
          });
        }
        
        const group = weekMap.get(key)!;
        if ((item as any).is_organic !== false) {
          group.organic.push(item);
        } else {
          group.conventional.push(item);
        }
      }
    });

    return Array.from(weekMap.entries()).map(([key, value]) => ({
      key,
      ...value,
    }));
  }, [displayedWeeksData, filterPengepul]);

  const displayTotalPages = Math.max(1, Math.ceil(displayWeeks.length / DISPLAY_PAGE_SIZE));
  const displayPageSafe = Math.min(displayPage, displayTotalPages);

  useEffect(() => {
    if (displayPage !== displayPageSafe) setDisplayPage(displayPageSafe);
  }, [displayPage, displayPageSafe]);

  const displayWeeksPaged = useMemo(() => {
    const start = (displayPageSafe - 1) * DISPLAY_PAGE_SIZE;
    return displayWeeks.slice(start, start + DISPLAY_PAGE_SIZE);
  }, [displayWeeks, displayPageSafe]);

  // Render farmer table for a list
  const renderFarmerTable = (list: PenjualanPetani[], title: string, icon: React.ReactNode) => {
    // Group by farmer
    const farmerMap = new Map<string, {
      nama: string;
      kode: string;
      dailyData: { date: string; value: number }[];
      total: number;
    }>();

    list.forEach(item => {
      const farmerId = item.petani_id;
      if (!farmerMap.has(farmerId)) {
        farmerMap.set(farmerId, {
          nama: item.petani?.nama || 'Unknown',
          kode: item.petani?.kode_petani || '-',
          dailyData: [],
          total: 0,
        });
      }
      const farmer = farmerMap.get(farmerId)!;
      farmer.dailyData.push({
        date: item.tanggal_jual,
        value: Number(item.jumlah_kg),
      });
      farmer.total += Number(item.jumlah_kg);
    });

    const farmers = Array.from(farmerMap.values());
    const totalAll = farmers.reduce((sum, f) => sum + f.total, 0);

    if (farmers.length === 0) return null;

    return (
      <div className="space-y-2">
        <div className="flex items-center gap-2 text-sm font-medium">
          {icon}
          <span>{title}</span>
          <Badge variant="outline">{farmers.length} petani</Badge>
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Kode</TableHead>
              <TableHead>Nama Petani</TableHead>
              <TableHead>Tanggal Penjualan</TableHead>
              <TableHead className="text-right">Total (Kg)</TableHead>
              <TableHead className="text-right">Aksi</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {farmers.sort((a, b) => a.kode.localeCompare(b.kode, undefined, { numeric: true, sensitivity: 'base' })).map((farmer, idx) => (
              <TableRow key={idx}>
                <TableCell className="font-mono text-sm">{farmer.kode}</TableCell>
                <TableCell className="font-medium">{farmer.nama}</TableCell>
                <TableCell className="text-sm">
                  <div className="flex flex-wrap gap-1">
                    {farmer.dailyData
                      .sort((a, b) => a.date.localeCompare(b.date))
                      .map((d, i) => (
                        <Badge key={i} variant="outline" className="text-xs">
                          {format(new Date(d.date), "dd/MM")} - {d.value} Kg
                        </Badge>
                      ))}
                  </div>
                </TableCell>
                <TableCell className="text-right font-bold">{farmer.total.toLocaleString()}</TableCell>
                <TableCell className="text-right">
                  <Button 
                    variant="ghost" 
                    size="icon"
                    onClick={() => {
                      const itemsToDelete = list.filter(i => i.petani_id === list.find(l => l.petani?.nama === farmer.nama)?.petani_id);
                      itemsToDelete.forEach(item => handleDelete(item.id));
                    }}
                  >
                    <Trash2 className="h-4 w-4 text-destructive" />
                  </Button>
                </TableCell>
              </TableRow>
            ))}
            <TableRow className="bg-muted/50">
              <TableCell colSpan={3} className="font-bold">Total</TableCell>
              <TableCell className="text-right font-bold">{totalAll.toLocaleString()} Kg</TableCell>
              <TableCell></TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    );
  };

  if (loading) {
    return <TableSkeleton rows={5} columns={6} />;
  }

  return (
    <div className="space-y-6">
      {/* Header Card */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between flex-wrap gap-4">
          <div>
            <CardTitle className="flex items-center gap-2">
              <ArrowDownToLine className="h-5 w-5" />
              Barang Masuk
            </CardTitle>
            <CardDescription>Penjualan petani ke pengepul dari data estimasi (per pengepul)</CardDescription>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            <Select value={filterPengepul} onValueChange={setFilterPengepul}>
              <SelectTrigger className="w-48">
                <SelectValue placeholder="Filter Pengepul" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Semua Pengepul</SelectItem>
                {pengepulList.map((p) => (
                  <SelectItem key={p.id} value={p.id}>{p.nama}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            
            {/* Delete per Estimation */}
            {estimationGroups.length > 0 && (
              <Button
                variant="outline"
                className="border-destructive text-destructive hover:bg-destructive/10"
                onClick={() => setDeleteDialogOpen(true)}
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Hapus per Estimasi ({estimationGroups.length})
              </Button>
            )}
            
            {/* Auto Generate Dialog */}
            <Dialog open={autoGenerateDialogOpen} onOpenChange={(open) => {
              setAutoGenerateDialogOpen(open);
              if (!open) {
                setSelectedWeeks(new Set());
              }
            }}>
              <DialogTrigger asChild>
                <Button variant="outline" className="border-primary text-primary hover:bg-primary/10">
                   <Sparkles className="h-4 w-4 mr-2" />
                   Auto Generate
                   {unprocessedWeeks.length > 0 && (
                     <span className="ml-2 bg-primary text-primary-foreground px-2 py-0.5 rounded-full text-xs">
                       {unprocessedWeeks.length} data
                     </span>
                   )}
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-5xl max-h-[85vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle className="flex items-center gap-2">
                    <Sparkles className="h-5 w-5 text-primary" />
                    Auto Generate dari Estimasi Panen
                  </DialogTitle>
                   <DialogDescription>
                     Pilih data estimasi yang akan diproses. Data penjualan akan dibuat per petani per hari berdasarkan pengepul.
                   </DialogDescription>
                </DialogHeader>

                {isLoadingEstimations ? (
                  <div className="text-center py-8">
                    <p className="text-muted-foreground">Memuat data estimasi...</p>
                  </div>
                ) : savedEstimations.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    <FileText className="h-12 w-12 mx-auto mb-3 opacity-50" />
                    <p className="font-medium">Belum ada data estimasi tersimpan</p>
                    <p className="text-sm">Buat dan simpan estimasi penjualan di tab Estimasi terlebih dahulu</p>
                  </div>
                ) : unprocessedWeeks.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    <Check className="h-12 w-12 mx-auto mb-3 text-green-500" />
                    <p className="font-medium">Semua minggu sudah diproses</p>
                    <p className="text-sm">Tidak ada data baru yang perlu dikonversi</p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {/* Progress Indicator */}
                    {autoGenerateLoading && generateProgress.total > 0 && (
                      <div className="p-4 bg-muted/50 rounded-lg space-y-2">
                        <div className="flex items-center justify-between text-sm">
                          <span className="flex items-center gap-2">
                            <Loader2 className="h-4 w-4 animate-spin" />
                            Memproses data...
                          </span>
                          <span className="font-medium">
                            {generateProgress.current} / {generateProgress.total}
                          </span>
                        </div>
                        <Progress value={(generateProgress.current / generateProgress.total) * 100} />
                      </div>
                    )}

                    {/* Select All */}
                    <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                      <div className="flex items-center gap-2">
                        <Checkbox
                          checked={selectedWeeks.size === unprocessedWeeks.length}
                          onCheckedChange={handleSelectAllWeeks}
                          disabled={autoGenerateLoading}
                        />
                        <span className="font-medium">Pilih Semua Data ({unprocessedWeeks.length})</span>
                      </div>
                      <Button 
                        onClick={handleAutoGenerate} 
                        disabled={selectedWeeks.size === 0 || autoGenerateLoading}
                      >
                        {autoGenerateLoading ? (
                          <>
                            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                            Memproses...
                          </>
                        ) : (
                          `Generate ${selectedWeeks.size} Data`
                        )}
                      </Button>
                    </div>

                    {/* Week Cards */}
                    {unprocessedWeeks.map(week => {
                      const weekKey = `${week.estimationId}-${week.weekIndex}`;
                      const isExpanded = expandedWeeks.has(weekKey);
                      const isSelected = selectedWeeks.has(weekKey);

                      return (
                        <Collapsible key={weekKey} open={isExpanded} onOpenChange={() => toggleWeek(weekKey)}>
                          <Card className={isSelected ? "border-primary" : ""}>
                            <CardHeader className="py-3">
                              <div className="flex items-center justify-between">
                                <div className="flex items-center gap-3">
                                  <Checkbox
                                    checked={isSelected}
                                    onCheckedChange={() => handleToggleWeekSelection(weekKey)}
                                  />
                                  <CollapsibleTrigger asChild>
                                    <Button variant="ghost" size="icon" className="h-6 w-6">
                                      {isExpanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
                                    </Button>
                                  </CollapsibleTrigger>
                                  <div>
                                    <p className="font-medium">{week.estimationName} - {week.weekLabel}</p>
                                    <p className="text-sm text-muted-foreground flex items-center gap-1">
                                      <Calendar className="h-3 w-3" />
                                      {format(new Date(week.startDate), "dd MMM", { locale: localeId })} - {format(new Date(week.endDate), "dd MMM yyyy", { locale: localeId })}
                                    </p>
                                  </div>
                                </div>
                                <div className="flex items-center gap-4">
                                  <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                                    <Leaf className="h-3 w-3 mr-1" />
                                    {week.totalOrganic.toLocaleString()} Kg
                                  </Badge>
                                  <Badge variant="outline" className="bg-orange-50 text-orange-700 border-orange-200">
                                    <Factory className="h-3 w-3 mr-1" />
                                    {week.totalConventional.toLocaleString()} Kg
                                  </Badge>
                                </div>
                              </div>
                            </CardHeader>
                            <CollapsibleContent>
                              <CardContent className="pt-0">
                                <div className="grid grid-cols-2 gap-6">
                                  {/* Organic Table */}
                                  {week.farmersOrganic.length > 0 && (
                                    <div className="space-y-2">
                                      <div className="flex items-center gap-2 text-sm font-medium text-green-700">
                                        <Leaf className="h-4 w-4" />
                                        Produk Organik ({week.farmersOrganic.length} petani)
                                      </div>
                                      <Table>
                                        <TableHeader>
                                          <TableRow>
                                            <TableHead>Nama Petani</TableHead>
                                            <TableHead>Kode</TableHead>
                                            {[1, 2, 3, 4, 5, 6, 7].map(d => (
                                              <TableHead key={d} className="text-center w-12">H{d}</TableHead>
                                            ))}
                                            <TableHead className="text-right">Total</TableHead>
                                          </TableRow>
                                        </TableHeader>
                                        <TableBody>
                                          {week.farmersOrganic.map(farmer => (
                                            <TableRow key={farmer.farmerId}>
                                              <TableCell className="font-medium">{farmer.farmerName}</TableCell>
                                              <TableCell>{farmer.farmerCode}</TableCell>
                                              {farmer.dailyValues.map((val, idx) => (
                                                <TableCell key={idx} className="text-center text-sm">
                                                  {val > 0 ? val.toLocaleString() : '-'}
                                                </TableCell>
                                              ))}
                                              <TableCell className="text-right font-bold">{farmer.total.toLocaleString()}</TableCell>
                                            </TableRow>
                                          ))}
                                        </TableBody>
                                      </Table>
                                    </div>
                                  )}

                                  {/* Conventional Table */}
                                  {week.farmersConventional.length > 0 && (
                                    <div className="space-y-2">
                                      <div className="flex items-center gap-2 text-sm font-medium text-orange-700">
                                        <Factory className="h-4 w-4" />
                                        Produk Konvensional ({week.farmersConventional.length} petani)
                                      </div>
                                      <Table>
                                        <TableHeader>
                                          <TableRow>
                                            <TableHead>Nama Petani</TableHead>
                                            <TableHead>Kode</TableHead>
                                            {[1, 2, 3, 4, 5, 6, 7].map(d => (
                                              <TableHead key={d} className="text-center w-12">H{d}</TableHead>
                                            ))}
                                            <TableHead className="text-right">Total</TableHead>
                                          </TableRow>
                                        </TableHeader>
                                        <TableBody>
                                          {week.farmersConventional.map(farmer => (
                                            <TableRow key={farmer.farmerId}>
                                              <TableCell className="font-medium">{farmer.farmerName}</TableCell>
                                              <TableCell>{farmer.farmerCode}</TableCell>
                                              {farmer.dailyValues.map((val, idx) => (
                                                <TableCell key={idx} className="text-center text-sm">
                                                  {val > 0 ? val.toLocaleString() : '-'}
                                                </TableCell>
                                              ))}
                                              <TableCell className="text-right font-bold">{farmer.total.toLocaleString()}</TableCell>
                                            </TableRow>
                                          ))}
                                        </TableBody>
                                      </Table>
                                    </div>
                                  )}
                                </div>
                              </CardContent>
                            </CollapsibleContent>
                          </Card>
                        </Collapsible>
                      );
                    })}
                  </div>
                )}
              </DialogContent>
            </Dialog>

            <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
              <DialogTrigger asChild>
                <Button className="bg-gradient-organic">
                  <Plus className="h-4 w-4 mr-2" />
                  Tambah Manual
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Tambah Barang Masuk Manual</DialogTitle>
                  <DialogDescription>Input penjualan petani ke pengepul secara manual</DialogDescription>
                </DialogHeader>
                <div className="space-y-4">
                  <div>
                    <Label>Pengepul *</Label>
                    <Select value={form.pengepul_id} onValueChange={handlePengepulChange}>
                      <SelectTrigger><SelectValue placeholder="Pilih pengepul" /></SelectTrigger>
                      <SelectContent>
                        {pengepulList.map(p => (
                          <SelectItem key={p.id} value={p.id}>{p.nama}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label>Petani *</Label>
                    <Select value={form.petani_id} onValueChange={(v) => setForm(prev => ({ ...prev, petani_id: v }))}>
                      <SelectTrigger><SelectValue placeholder="Pilih petani" /></SelectTrigger>
                      <SelectContent>
                        {filteredFarmers.map(f => (
                          <SelectItem key={f.id} value={f.id}>{f.nama} ({f.kode_petani})</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label>Tanggal Jual</Label>
                      <Input type="date" value={form.tanggal_jual} onChange={e => setForm(prev => ({ ...prev, tanggal_jual: e.target.value }))} />
                    </div>
                    <div>
                      <Label>Jumlah (Kg) *</Label>
                      <Input type="number" value={form.jumlah_kg} onChange={e => setForm(prev => ({ ...prev, jumlah_kg: e.target.value }))} />
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label>Harga/Kg *</Label>
                      <Input type="number" value={form.harga_per_kg} onChange={e => setForm(prev => ({ ...prev, harga_per_kg: e.target.value }))} />
                    </div>
                    <div>
                      <Label>Tipe Produk</Label>
                      <Select value={form.is_organic ? "organic" : "conventional"} onValueChange={v => setForm(prev => ({ ...prev, is_organic: v === "organic" }))}>
                        <SelectTrigger><SelectValue /></SelectTrigger>
                        <SelectContent>
                          <SelectItem value="organic">Organik</SelectItem>
                          <SelectItem value="conventional">Konvensional</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <Button onClick={handleSubmit} className="w-full">Simpan</Button>
                </div>
              </DialogContent>
            </Dialog>
          </div>
        </CardHeader>
      </Card>

      {/* Delete Estimation Dialog */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Hapus Data Estimasi</AlertDialogTitle>
            <AlertDialogDescription>
              Pilih estimasi yang datanya akan dihapus dari barang masuk.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="space-y-2 max-h-64 overflow-y-auto">
            {estimationGroups.map(group => (
              <div
                key={group.estimationName}
                className={`p-3 border rounded-lg cursor-pointer hover:border-destructive ${deletingEstimation?.estimationName === group.estimationName ? 'border-destructive bg-destructive/5' : ''}`}
                onClick={() => setDeletingEstimation(group)}
              >
                <div className="font-medium">{group.estimationName}</div>
                <div className="text-sm text-muted-foreground">
                  {group.count} entri • {group.totalKg.toLocaleString()} Kg
                </div>
              </div>
            ))}
          </div>
          <AlertDialogFooter>
            <AlertDialogCancel>Batal</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDeleteEstimationGroup}
              disabled={!deletingEstimation || isDeleting}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {isDeleting ? "Menghapus..." : "Hapus"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Display Data per Week */}
      {totalCount === 0 && !isLoadingDisplay ? (
        <Card className="p-8 text-center text-muted-foreground">
          <ArrowDownToLine className="h-12 w-12 mx-auto mb-3 opacity-50" />
          <p className="font-medium">Belum ada data barang masuk</p>
          <p className="text-sm">Gunakan Auto Generate untuk membuat data dari estimasi penjualan</p>
        </Card>
      ) : isLoadingDisplay ? (
        <TableSkeleton rows={5} columns={6} />
      ) : (
         <div className="space-y-4">
           <div className="text-sm text-muted-foreground flex items-center justify-between gap-3">
             <span>
               Menampilkan {displayWeeksPaged.length} dari {displayWeeks.length} minggu
             </span>
             {weekProgressLoading && <span className="text-xs">Memperbarui status…</span>}
           </div>

           {displayWeeksPaged.map(weekGroup => (
             <Card key={weekGroup.key}>
               <CardHeader className="py-3">
                 <CardTitle className="text-lg flex items-center gap-2">
                   <Calendar className="h-5 w-5" />
                   {weekGroup.estimationName} - {weekGroup.weekLabel}
                 </CardTitle>
               </CardHeader>
               <CardContent>
                 <div className="grid grid-cols-2 gap-6">
                   {renderFarmerTable(
                     weekGroup.organic,
                     "Produk Organik",
                     <Leaf className="h-4 w-4 text-green-600" />
                   )}
                   {renderFarmerTable(
                     weekGroup.conventional,
                     "Produk Konvensional",
                     <Factory className="h-4 w-4 text-orange-500" />
                   )}
                 </div>
               </CardContent>
             </Card>
           ))}

           {displayTotalPages > 1 && (
             <div className="pt-2">
               <Pagination>
                 <PaginationContent>
                   <PaginationItem>
                     <PaginationPrevious
                       href="#"
                       onClick={(e) => {
                         e.preventDefault();
                         setDisplayPage((p) => Math.max(1, p - 1));
                       }}
                       className={displayPageSafe === 1 ? "pointer-events-none opacity-50" : ""}
                     />
                   </PaginationItem>

                   <PaginationItem>
                     <span className="px-3 text-sm text-muted-foreground">
                       Halaman {displayPageSafe} / {displayTotalPages}
                     </span>
                   </PaginationItem>

                   <PaginationItem>
                     <PaginationNext
                       href="#"
                       onClick={(e) => {
                         e.preventDefault();
                         setDisplayPage((p) => Math.min(displayTotalPages, p + 1));
                       }}
                       className={displayPageSafe === displayTotalPages ? "pointer-events-none opacity-50" : ""}
                     />
                   </PaginationItem>
                 </PaginationContent>
               </Pagination>
             </div>
           )}
         </div>
      )}
    </div>
  );
};
