import { useState, useEffect, useMemo } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Checkbox } from "@/components/ui/checkbox";
import { ArrowUpFromLine, Trash2, Wand2, ChevronDown, ChevronRight, Leaf, Factory, Calendar, FileText, Check, Package } from "lucide-react";
import { usePengambilanKoperasi } from "@/hooks/use-pengambilan-koperasi";
import { usePenjualanPetani } from "@/hooks/use-penjualan-petani";
import { usePengepul } from "@/hooks/use-pengepul";
import { useFarmers } from "@/hooks/use-farmers";
import { TableSkeleton } from "@/components/ui/skeleton-templates";
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";
import { format, addDays } from "date-fns";
import { id as localeId } from "date-fns/locale";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { SavedEstimation, FarmerWeeklyData } from "@/hooks/use-harvest-estimation";

interface WeekData {
  estimationId: string;
  estimationName: string;
  weekIndex: number;
  weekLabel: string;
  startDate: string;
  endDate: string;
  pickupDate: string;
  farmersOrganic: FarmerWeekEntry[];
  farmersConventional: FarmerWeekEntry[];
  totalOrganic: number;
  totalConventional: number;
  isProcessed: boolean;
  pengepulSummary: PengepulSummary[];
}

interface FarmerWeekEntry {
  farmerId: string;
  farmerName: string;
  farmerCode: string;
  pengepulId: string;
  pengepulName: string;
  dailyValues: number[];
  dailyDates: string[];
  total: number;
  isOrganic: boolean;
}

interface PengepulSummary {
  pengepulId: string;
  pengepulName: string;
  organicKg: number;
  conventionalKg: number;
  totalKg: number;
  farmerCount: number;
}

interface DisplayWeek {
  weekKey: string;
  estimationName: string;
  weekLabel: string;
  startDate: string;
  endDate: string;
  farmersOrganic: {
    farmerId: string;
    farmerName: string;
    farmerCode: string;
    pengepulName: string;
    dailyValues: number[];
    total: number;
  }[];
  farmersConventional: {
    farmerId: string;
    farmerName: string;
    farmerCode: string;
    pengepulName: string;
    dailyValues: number[];
    total: number;
  }[];
  totalOrganic: number;
  totalConventional: number;
  pengepulSummary: PengepulSummary[];
}

export const BarangKeluarTab = () => {
  const { pengambilanList, loading, addPengambilan, deletePengambilan, refetch } = usePengambilanKoperasi();
  const { penjualanList } = usePenjualanPetani();
  const { pengepulList } = usePengepul();
  const { farmers } = useFarmers();
  
  const [autoGenerateDialogOpen, setAutoGenerateDialogOpen] = useState(false);
  const [filterPengepul, setFilterPengepul] = useState<string>("all");
  const [generatingAuto, setGeneratingAuto] = useState(false);
  const [expandedWeeks, setExpandedWeeks] = useState<Set<string>>(new Set());
  const [selectedWeeks, setSelectedWeeks] = useState<Set<string>>(new Set());
  const [viewMode, setViewMode] = useState<'weekly' | 'summary'>('weekly');
  
  const [savedEstimations, setSavedEstimations] = useState<SavedEstimation[]>([]);
  const [isLoadingEstimations, setIsLoadingEstimations] = useState(false);
  
  // Pagination state
  const DISPLAY_PAGE_SIZE = 4;
  const [displayPage, setDisplayPage] = useState(1);

  // Load saved estimations
  useEffect(() => {
    const loadEstimations = async () => {
      setIsLoadingEstimations(true);
      try {
        const { data, error } = await supabase
          .from("estimasi_panen")
          .select("*")
          .order("created_at", { ascending: false });

        if (error) throw error;
        setSavedEstimations(data as unknown as SavedEstimation[]);
      } catch (error) {
        console.error("Error loading estimations:", error);
      } finally {
        setIsLoadingEstimations(false);
      }
    };
    loadEstimations();
  }, []);

  // Process penjualan_petani data into weekly structure (sama dengan barang masuk)
  const weeklyDataFromPenjualan = useMemo((): WeekData[] => {
    const weeks: WeekData[] = [];
    
    // Group penjualan by estimation and week
    const weekMap = new Map<string, {
      estimationId: string;
      estimationName: string;
      weekIndex: number;
      weekLabel: string;
      startDate: string;
      endDate: string;
      items: typeof penjualanList;
    }>();

    penjualanList.forEach(item => {
      const match = item.catatan?.match(/Auto-generated dari estimasi: (.+?) - (Minggu (\d+))/);
      if (match) {
        const [, estName, weekLabel, weekNum] = match;
        const weekIndex = parseInt(weekNum) - 1;
        const estimation = savedEstimations.find(e => e.nama_estimasi === estName);
        const key = `${estName}-${weekLabel}`;
        
        if (!weekMap.has(key)) {
          // Get dates from estimation
          let startDate = item.tanggal_jual;
          let endDate = item.tanggal_jual;
          
          if (estimation) {
            const panenData = estimation.data_panen as unknown as Array<{
              weekIndex: number;
              startDate: string;
              endDate: string;
              farmersData: FarmerWeeklyData[];
            }>;
            const weekData = panenData?.find(w => w.weekIndex === weekIndex);
            if (weekData) {
              startDate = weekData.startDate;
              endDate = weekData.endDate;
            }
          }
          
          weekMap.set(key, {
            estimationId: estimation?.id || '',
            estimationName: estName,
            weekIndex,
            weekLabel,
            startDate,
            endDate,
            items: [],
          });
        }
        
        weekMap.get(key)!.items.push(item);
      }
    });

    // Convert to WeekData
    weekMap.forEach((data, key) => {
      const farmersOrganic: FarmerWeekEntry[] = [];
      const farmersConventional: FarmerWeekEntry[] = [];
      const farmerMap = new Map<string, FarmerWeekEntry>();

      // Group items by farmer
      data.items.forEach(item => {
        const farmer = farmers.find(f => f.id === item.petani_id);
        const pengepul = pengepulList.find(p => p.id === item.pengepul_id);
        const isOrganic = (item as any).is_organic !== false;
        const farmerId = item.petani_id;
        const mapKey = `${farmerId}-${isOrganic}`;

        if (!farmerMap.has(mapKey)) {
          farmerMap.set(mapKey, {
            farmerId,
            farmerName: item.petani?.nama || farmer?.nama || 'Unknown',
            farmerCode: item.petani?.kode_petani || farmer?.kode_petani || '-',
            pengepulId: item.pengepul_id,
            pengepulName: pengepul?.nama || 'Unknown',
            dailyValues: [0, 0, 0, 0, 0, 0, 0],
            dailyDates: [],
            total: 0,
            isOrganic,
          });
        }

        const entry = farmerMap.get(mapKey)!;
        
        // Calculate day index from date
        const itemDate = new Date(item.tanggal_jual);
        const startDate = new Date(data.startDate);
        const dayIndex = Math.floor((itemDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
        
        if (dayIndex >= 0 && dayIndex < 7) {
          entry.dailyValues[dayIndex] = Number(item.jumlah_kg);
        }
        entry.total += Number(item.jumlah_kg);
        if (!entry.dailyDates.includes(item.tanggal_jual)) {
          entry.dailyDates.push(item.tanggal_jual);
        }
      });

      farmerMap.forEach(entry => {
        if (entry.isOrganic) {
          farmersOrganic.push(entry);
        } else {
          farmersConventional.push(entry);
        }
      });

      // Calculate pengepul summary
      const pengepulSummaryMap = new Map<string, PengepulSummary>();
      [...farmersOrganic, ...farmersConventional].forEach(f => {
        if (!pengepulSummaryMap.has(f.pengepulId)) {
          pengepulSummaryMap.set(f.pengepulId, {
            pengepulId: f.pengepulId,
            pengepulName: f.pengepulName,
            organicKg: 0,
            conventionalKg: 0,
            totalKg: 0,
            farmerCount: 0,
          });
        }
        const summary = pengepulSummaryMap.get(f.pengepulId)!;
        if (f.isOrganic) {
          summary.organicKg += f.total;
        } else {
          summary.conventionalKg += f.total;
        }
        summary.totalKg += f.total;
        summary.farmerCount++;
      });

      // Check if already processed (has pengambilan_koperasi entries)
      const isProcessed = pengambilanList.some(p => 
        p.catatan?.includes(data.estimationName) &&
        p.catatan?.includes(data.weekLabel)
      );

      const pickupDate = format(addDays(new Date(data.endDate), 1), "yyyy-MM-dd");

      weeks.push({
        estimationId: data.estimationId,
        estimationName: data.estimationName,
        weekIndex: data.weekIndex,
        weekLabel: data.weekLabel,
        startDate: data.startDate,
        endDate: data.endDate,
        pickupDate,
        farmersOrganic,
        farmersConventional,
        totalOrganic: farmersOrganic.reduce((sum, f) => sum + f.total, 0),
        totalConventional: farmersConventional.reduce((sum, f) => sum + f.total, 0),
        isProcessed,
        pengepulSummary: Array.from(pengepulSummaryMap.values()),
      });
    });

    return weeks.sort((a, b) => a.startDate.localeCompare(b.startDate));
  }, [penjualanList, savedEstimations, farmers, pengepulList, pengambilanList]);

  const unprocessedWeeks = weeklyDataFromPenjualan.filter(w => !w.isProcessed);
  const processedWeeks = weeklyDataFromPenjualan.filter(w => w.isProcessed);

  const toggleWeek = (weekKey: string) => {
    setExpandedWeeks(prev => {
      const newSet = new Set(prev);
      if (newSet.has(weekKey)) {
        newSet.delete(weekKey);
      } else {
        newSet.add(weekKey);
      }
      return newSet;
    });
  };

  const handleToggleWeekSelection = (weekKey: string) => {
    setSelectedWeeks(prev => {
      const newSet = new Set(prev);
      if (newSet.has(weekKey)) {
        newSet.delete(weekKey);
      } else {
        newSet.add(weekKey);
      }
      return newSet;
    });
  };

  const handleSelectAllWeeks = () => {
    if (selectedWeeks.size === unprocessedWeeks.length) {
      setSelectedWeeks(new Set());
    } else {
      setSelectedWeeks(new Set(unprocessedWeeks.map(w => `${w.estimationId}-${w.weekIndex}`)));
    }
  };

  const handleAutoGenerate = async () => {
    if (selectedWeeks.size === 0) {
      toast({
        title: "Pilih Minggu",
        description: "Pilih minimal satu minggu untuk diproses",
        variant: "destructive",
      });
      return;
    }

    setGeneratingAuto(true);
    let successCount = 0;

    for (const weekKey of selectedWeeks) {
      const week = weeklyDataFromPenjualan.find(w => `${w.estimationId}-${w.weekIndex}` === weekKey);
      if (!week) continue;

      // Group by pengepul and organic status
      const pengepulGroups = new Map<string, {
        pengepulId: string;
        isOrganic: boolean;
        totalKg: number;
        farmers: { id: string; name: string; code: string; kg: number; dailyValues: number[] }[];
      }>();

      const allFarmers = [...week.farmersOrganic, ...week.farmersConventional];

      allFarmers.forEach(farmer => {
        const key = `${farmer.pengepulId}-${farmer.isOrganic ? 'organic' : 'conventional'}`;
        
        if (!pengepulGroups.has(key)) {
          pengepulGroups.set(key, {
            pengepulId: farmer.pengepulId,
            isOrganic: farmer.isOrganic,
            totalKg: 0,
            farmers: [],
          });
        }

        const group = pengepulGroups.get(key)!;
        group.totalKg += farmer.total;
        group.farmers.push({
          id: farmer.farmerId,
          name: farmer.farmerName,
          code: farmer.farmerCode,
          kg: farmer.total,
          dailyValues: farmer.dailyValues,
        });
      });

      // Create pengambilan for each pengepul group
      for (const [, group] of pengepulGroups) {
        await addPengambilan({
          pengepul_id: group.pengepulId,
          tanggal_ambil: week.pickupDate,
          jumlah_kg: Math.round(group.totalKg * 10) / 10,
          batch_id: null,
          catatan: `Auto-generated dari estimasi: ${week.estimationName} - ${week.weekLabel} (${group.isOrganic ? 'Organik' : 'Konvensional'})`,
          is_organic: group.isOrganic,
          lot_number: `LOT-${format(new Date(week.pickupDate), "yyyyMMdd")}-${group.isOrganic ? 'ORG' : 'CNV'}`,
          detail_petani: group.farmers.map(f => ({
            petani_id: f.id,
            petani_nama: f.name,
            petani_kode: f.code,
            jumlah_kg: f.kg,
            daily_values: f.dailyValues,
          })),
        } as any);
        successCount++;
      }
    }

    setGeneratingAuto(false);
    setSelectedWeeks(new Set());
    setAutoGenerateDialogOpen(false);
    refetch();

    toast({
      title: "Berhasil",
      description: `${successCount} data barang keluar berhasil ditambahkan`,
    });
  };

  const handleDeleteWeek = async (week: WeekData) => {
    if (!confirm(`Yakin ingin menghapus semua data barang keluar untuk ${week.estimationName} - ${week.weekLabel}?`)) {
      return;
    }

    const itemsToDelete = pengambilanList.filter(p => 
      p.catatan?.includes(week.estimationName) &&
      p.catatan?.includes(week.weekLabel)
    );

    for (const item of itemsToDelete) {
      await deletePengambilan(item.id);
    }

    refetch();
    toast({
      title: "Berhasil",
      description: `Data barang keluar ${week.estimationName} - ${week.weekLabel} berhasil dihapus`,
    });
  };

  // Filter data by pengepul
  const filteredWeeks = useMemo(() => {
    if (filterPengepul === "all") return processedWeeks;
    
    return processedWeeks.map(week => ({
      ...week,
      farmersOrganic: week.farmersOrganic.filter(f => f.pengepulId === filterPengepul),
      farmersConventional: week.farmersConventional.filter(f => f.pengepulId === filterPengepul),
      pengepulSummary: week.pengepulSummary.filter(p => p.pengepulId === filterPengepul),
    })).filter(week => 
      week.farmersOrganic.length > 0 || week.farmersConventional.length > 0
    );
  }, [processedWeeks, filterPengepul]);

  // Pagination for filtered weeks
  const totalPages = Math.ceil(filteredWeeks.length / DISPLAY_PAGE_SIZE);
  const paginatedWeeks = useMemo(() => {
    const startIndex = (displayPage - 1) * DISPLAY_PAGE_SIZE;
    return filteredWeeks.slice(startIndex, startIndex + DISPLAY_PAGE_SIZE);
  }, [filteredWeeks, displayPage]);

  // Reset page when filter changes
  useEffect(() => {
    setDisplayPage(1);
  }, [filterPengepul]);

  // Render farmer table
  const renderFarmerTable = (
    farmers: FarmerWeekEntry[], 
    title: string, 
    icon: React.ReactNode, 
    colorClass: string
  ) => {
    if (farmers.length === 0) return null;
    const total = farmers.reduce((sum, f) => sum + f.total, 0);

    return (
      <div className="space-y-2">
        <div className={`flex items-center gap-2 text-sm font-medium ${colorClass}`}>
          {icon}
          {title} ({farmers.length} petani)
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Nama Petani</TableHead>
              <TableHead>Kode</TableHead>
              {[1, 2, 3, 4, 5, 6, 7].map(d => (
                <TableHead key={d} className="text-center w-12">H{d}</TableHead>
              ))}
              <TableHead className="text-right">Total</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {farmers.map(farmer => (
              <TableRow key={farmer.farmerId}>
                <TableCell className="font-medium">{farmer.farmerName}</TableCell>
                <TableCell>{farmer.farmerCode}</TableCell>
                {farmer.dailyValues.map((val, idx) => (
                  <TableCell key={idx} className="text-center text-sm">
                    {val > 0 ? val.toLocaleString() : '-'}
                  </TableCell>
                ))}
                <TableCell className="text-right font-bold">{farmer.total.toLocaleString()}</TableCell>
              </TableRow>
            ))}
            <TableRow className="bg-muted/50">
              <TableCell colSpan={9} className="font-bold">Total</TableCell>
              <TableCell className="text-right font-bold">{total.toLocaleString()} Kg</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    );
  };

  if (loading) {
    return <TableSkeleton rows={5} columns={6} />;
  }

  return (
    <div className="space-y-6">
      {/* Header Card */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between flex-wrap gap-4">
          <div>
            <CardTitle className="flex items-center gap-2">
              <ArrowUpFromLine className="h-5 w-5" />
              Barang Keluar
            </CardTitle>
            <CardDescription>
              Pengambilan oleh koperasi dari pengepul (hari ke-8 setelah minggu penjualan)
            </CardDescription>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            <Select value={filterPengepul} onValueChange={setFilterPengepul}>
              <SelectTrigger className="w-48">
                <SelectValue placeholder="Filter Pengepul" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Semua Pengepul</SelectItem>
                {pengepulList.map((p) => (
                  <SelectItem key={p.id} value={p.id}>{p.nama}</SelectItem>
                ))}
              </SelectContent>
            </Select>

            <Select value={viewMode} onValueChange={(v: 'weekly' | 'summary') => setViewMode(v)}>
              <SelectTrigger className="w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="weekly">Per Minggu</SelectItem>
                <SelectItem value="summary">Rekap Pengepul</SelectItem>
              </SelectContent>
            </Select>
            
            {/* Auto Generate Dialog */}
            <Dialog open={autoGenerateDialogOpen} onOpenChange={(open) => {
              setAutoGenerateDialogOpen(open);
              if (!open) {
                setSelectedWeeks(new Set());
              }
            }}>
              <DialogTrigger asChild>
                <Button variant="outline" className="border-primary text-primary hover:bg-primary/10">
                  <Wand2 className="h-4 w-4 mr-2" />
                  Auto Generate
                  {unprocessedWeeks.length > 0 && (
                    <span className="ml-2 bg-primary text-primary-foreground px-2 py-0.5 rounded-full text-xs">
                      {unprocessedWeeks.length} minggu
                    </span>
                  )}
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-5xl max-h-[85vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle className="flex items-center gap-2">
                    <Wand2 className="h-5 w-5 text-primary" />
                    Auto Generate Barang Keluar
                  </DialogTitle>
                  <DialogDescription>
                    Pilih minggu dari data barang masuk yang akan diproses menjadi barang keluar (pengambilan koperasi).
                  </DialogDescription>
                </DialogHeader>

                {isLoadingEstimations ? (
                  <div className="text-center py-8">
                    <p className="text-muted-foreground">Memuat data...</p>
                  </div>
                ) : unprocessedWeeks.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    <Check className="h-12 w-12 mx-auto mb-3 text-green-500" />
                    <p className="font-medium">Semua minggu sudah diproses</p>
                    <p className="text-sm">Tidak ada data barang masuk baru yang perlu dikonversi</p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {/* Select All */}
                    <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                      <div className="flex items-center gap-2">
                        <Checkbox
                          checked={selectedWeeks.size === unprocessedWeeks.length}
                          onCheckedChange={handleSelectAllWeeks}
                        />
                        <span className="font-medium">Pilih Semua Minggu ({unprocessedWeeks.length})</span>
                      </div>
                      <Button 
                        onClick={handleAutoGenerate} 
                        disabled={selectedWeeks.size === 0 || generatingAuto}
                      >
                        {generatingAuto ? "Memproses..." : `Generate ${selectedWeeks.size} Minggu`}
                      </Button>
                    </div>

                    {/* Week Cards */}
                    {unprocessedWeeks.map(week => {
                      const weekKey = `${week.estimationId}-${week.weekIndex}`;
                      const isExpanded = expandedWeeks.has(weekKey);
                      const isSelected = selectedWeeks.has(weekKey);

                      return (
                        <Collapsible key={weekKey} open={isExpanded} onOpenChange={() => toggleWeek(weekKey)}>
                          <Card className={isSelected ? "border-primary" : ""}>
                            <CardHeader className="py-3">
                              <div className="flex items-center justify-between">
                                <div className="flex items-center gap-3">
                                  <Checkbox
                                    checked={isSelected}
                                    onCheckedChange={() => handleToggleWeekSelection(weekKey)}
                                  />
                                  <CollapsibleTrigger asChild>
                                    <Button variant="ghost" size="icon" className="h-6 w-6">
                                      {isExpanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
                                    </Button>
                                  </CollapsibleTrigger>
                                  <div>
                                    <p className="font-medium">{week.estimationName} - {week.weekLabel}</p>
                                    <p className="text-sm text-muted-foreground flex items-center gap-1">
                                      <Calendar className="h-3 w-3" />
                                      {format(new Date(week.startDate), "dd MMM", { locale: localeId })} - {format(new Date(week.endDate), "dd MMM yyyy", { locale: localeId })}
                                      <span className="mx-1">→</span>
                                      Ambil: {format(new Date(week.pickupDate), "dd MMM yyyy", { locale: localeId })}
                                    </p>
                                  </div>
                                </div>
                                <div className="flex items-center gap-4">
                                  <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                                    <Leaf className="h-3 w-3 mr-1" />
                                    {week.totalOrganic.toLocaleString()} Kg
                                  </Badge>
                                  <Badge variant="outline" className="bg-orange-50 text-orange-700 border-orange-200">
                                    <Factory className="h-3 w-3 mr-1" />
                                    {week.totalConventional.toLocaleString()} Kg
                                  </Badge>
                                </div>
                              </div>
                            </CardHeader>
                            <CollapsibleContent>
                              <CardContent className="pt-0 space-y-4">
                                {/* Pengepul Summary */}
                                {week.pengepulSummary.length > 0 && (
                                  <div className="bg-muted/30 p-3 rounded-lg">
                                    <p className="text-sm font-medium mb-2 flex items-center gap-2">
                                      <Package className="h-4 w-4" />
                                      Rekap per Pengepul:
                                    </p>
                                    <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
                                      {week.pengepulSummary.map(p => (
                                        <div key={p.pengepulId} className="bg-background p-2 rounded border">
                                          <p className="font-medium text-sm">{p.pengepulName}</p>
                                          <p className="text-xs text-muted-foreground">
                                            {p.farmerCount} petani • {p.totalKg.toLocaleString()} Kg
                                          </p>
                                          <div className="flex gap-2 mt-1">
                                            {p.organicKg > 0 && (
                                              <Badge variant="outline" className="text-xs bg-green-50 text-green-700">
                                                Org: {p.organicKg.toLocaleString()}
                                              </Badge>
                                            )}
                                            {p.conventionalKg > 0 && (
                                              <Badge variant="outline" className="text-xs bg-orange-50 text-orange-700">
                                                Knv: {p.conventionalKg.toLocaleString()}
                                              </Badge>
                                            )}
                                          </div>
                                        </div>
                                      ))}
                                    </div>
                                  </div>
                                )}

                                <div className="grid grid-cols-2 gap-6">
                                  {renderFarmerTable(
                                    week.farmersOrganic,
                                    "Produk Organik",
                                    <Leaf className="h-4 w-4" />,
                                    "text-green-700"
                                  )}
                                  {renderFarmerTable(
                                    week.farmersConventional,
                                    "Produk Konvensional",
                                    <Factory className="h-4 w-4" />,
                                    "text-orange-700"
                                  )}
                                </div>
                              </CardContent>
                            </CollapsibleContent>
                          </Card>
                        </Collapsible>
                      );
                    })}
                  </div>
                )}
              </DialogContent>
            </Dialog>
          </div>
        </CardHeader>
      </Card>

      {/* Content based on view mode */}
      {viewMode === 'weekly' ? (
        // Weekly View - show processed weeks with pagination
        <div className="space-y-4">
          {filteredWeeks.length === 0 ? (
            <Card>
              <CardContent className="py-8 text-center text-muted-foreground">
                <FileText className="h-12 w-12 mx-auto mb-3 opacity-50" />
                <p className="font-medium">Belum ada data barang keluar</p>
                <p className="text-sm">Gunakan Auto Generate untuk membuat data dari barang masuk</p>
              </CardContent>
            </Card>
          ) : (
            <>
              {/* Pagination Info */}
              <div className="flex items-center justify-between px-2">
                <p className="text-sm text-muted-foreground">
                  Menampilkan {((displayPage - 1) * DISPLAY_PAGE_SIZE) + 1} - {Math.min(displayPage * DISPLAY_PAGE_SIZE, filteredWeeks.length)} dari {filteredWeeks.length} minggu
                </p>
                {totalPages > 1 && (
                  <Pagination>
                    <PaginationContent>
                      <PaginationItem>
                        <PaginationPrevious 
                          onClick={() => setDisplayPage(p => Math.max(1, p - 1))}
                          className={displayPage === 1 ? "pointer-events-none opacity-50" : "cursor-pointer"}
                        />
                      </PaginationItem>
                      <PaginationItem>
                        <span className="px-4 py-2 text-sm">
                          Halaman {displayPage} dari {totalPages}
                        </span>
                      </PaginationItem>
                      <PaginationItem>
                        <PaginationNext 
                          onClick={() => setDisplayPage(p => Math.min(totalPages, p + 1))}
                          className={displayPage === totalPages ? "pointer-events-none opacity-50" : "cursor-pointer"}
                        />
                      </PaginationItem>
                    </PaginationContent>
                  </Pagination>
                )}
              </div>

              {/* Week Cards */}
              {paginatedWeeks.map(week => {
                const weekKey = `display-${week.estimationId}-${week.weekIndex}`;
                const isExpanded = expandedWeeks.has(weekKey);
                const totalKg = week.totalOrganic + week.totalConventional;

                return (
                  <Collapsible key={weekKey} open={isExpanded} onOpenChange={() => toggleWeek(weekKey)}>
                    <Card>
                      <CardHeader className="py-3">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-3">
                            <CollapsibleTrigger asChild>
                              <Button variant="ghost" size="icon" className="h-6 w-6">
                                {isExpanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
                              </Button>
                            </CollapsibleTrigger>
                            <div>
                              <p className="font-medium">{week.estimationName} - {week.weekLabel}</p>
                              <p className="text-sm text-muted-foreground flex items-center gap-1">
                                <Calendar className="h-3 w-3" />
                                {format(new Date(week.startDate), "dd MMM", { locale: localeId })} - {format(new Date(week.endDate), "dd MMM yyyy", { locale: localeId })}
                              </p>
                            </div>
                          </div>
                          <div className="flex items-center gap-4">
                            <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                              <Leaf className="h-3 w-3 mr-1" />
                              {week.totalOrganic.toLocaleString()} Kg
                            </Badge>
                            <Badge variant="outline" className="bg-orange-50 text-orange-700 border-orange-200">
                              <Factory className="h-3 w-3 mr-1" />
                              {week.totalConventional.toLocaleString()} Kg
                            </Badge>
                            <Badge variant="secondary" className="text-lg">
                              Total: {totalKg.toLocaleString()} Kg
                            </Badge>
                            <Button 
                              variant="ghost" 
                              size="icon"
                              className="text-destructive hover:bg-destructive/10"
                              onClick={() => handleDeleteWeek(week)}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </div>
                        </div>
                      </CardHeader>
                      <CollapsibleContent>
                        <CardContent className="pt-0 space-y-4">
                          {/* Pengepul Summary */}
                          {week.pengepulSummary.length > 0 && (
                            <div className="bg-muted/30 p-3 rounded-lg">
                              <p className="text-sm font-medium mb-2 flex items-center gap-2">
                                <Package className="h-4 w-4" />
                                Rekap per Pengepul:
                              </p>
                              <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                                {week.pengepulSummary.map(p => (
                                  <div key={p.pengepulId} className="bg-background p-2 rounded border">
                                    <p className="font-medium text-sm">{p.pengepulName}</p>
                                    <p className="text-xs text-muted-foreground">
                                      {p.farmerCount} petani • {p.totalKg.toLocaleString()} Kg
                                    </p>
                                    <div className="flex gap-2 mt-1">
                                      {p.organicKg > 0 && (
                                        <Badge variant="outline" className="text-xs bg-green-50 text-green-700">
                                          Org: {p.organicKg.toLocaleString()}
                                        </Badge>
                                      )}
                                      {p.conventionalKg > 0 && (
                                        <Badge variant="outline" className="text-xs bg-orange-50 text-orange-700">
                                          Knv: {p.conventionalKg.toLocaleString()}
                                        </Badge>
                                      )}
                                    </div>
                                  </div>
                                ))}
                              </div>
                            </div>
                          )}

                          <div className="grid grid-cols-2 gap-6">
                            {renderFarmerTable(
                              week.farmersOrganic,
                              "Produk Organik",
                              <Leaf className="h-4 w-4" />,
                              "text-green-700"
                            )}
                            {renderFarmerTable(
                              week.farmersConventional,
                              "Produk Konvensional",
                              <Factory className="h-4 w-4" />,
                              "text-orange-700"
                            )}
                          </div>
                        </CardContent>
                      </CollapsibleContent>
                    </Card>
                  </Collapsible>
                );
              })}

              {/* Bottom Pagination */}
              {totalPages > 1 && (
                <div className="flex justify-center pt-4">
                  <Pagination>
                    <PaginationContent>
                      <PaginationItem>
                        <PaginationPrevious 
                          onClick={() => setDisplayPage(p => Math.max(1, p - 1))}
                          className={displayPage === 1 ? "pointer-events-none opacity-50" : "cursor-pointer"}
                        />
                      </PaginationItem>
                      <PaginationItem>
                        <span className="px-4 py-2 text-sm">
                          Halaman {displayPage} dari {totalPages}
                        </span>
                      </PaginationItem>
                      <PaginationItem>
                        <PaginationNext 
                          onClick={() => setDisplayPage(p => Math.min(totalPages, p + 1))}
                          className={displayPage === totalPages ? "pointer-events-none opacity-50" : "cursor-pointer"}
                        />
                      </PaginationItem>
                    </PaginationContent>
                  </Pagination>
                </div>
              )}
            </>
          )}
        </div>
      ) : (
        // Summary View - show totals per pengepul
        <Card>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Package className="h-5 w-5" />
              Rekap Total per Pengepul
            </CardTitle>
            <CardDescription>
              Total barang keluar dari semua minggu yang sudah diproses
            </CardDescription>
          </CardHeader>
          <CardContent>
            {filteredWeeks.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                <FileText className="h-12 w-12 mx-auto mb-3 opacity-50" />
                <p>Belum ada data barang keluar</p>
              </div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Pengepul</TableHead>
                    <TableHead className="text-right">Jumlah Petani</TableHead>
                    <TableHead className="text-right">Organik (Kg)</TableHead>
                    <TableHead className="text-right">Konvensional (Kg)</TableHead>
                    <TableHead className="text-right">Total (Kg)</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {(() => {
                    // Aggregate all pengepul summaries
                    const aggregated = new Map<string, PengepulSummary>();
                    
                    filteredWeeks.forEach(week => {
                      week.pengepulSummary.forEach(p => {
                        if (!aggregated.has(p.pengepulId)) {
                          aggregated.set(p.pengepulId, { ...p });
                        } else {
                          const existing = aggregated.get(p.pengepulId)!;
                          existing.organicKg += p.organicKg;
                          existing.conventionalKg += p.conventionalKg;
                          existing.totalKg += p.totalKg;
                          existing.farmerCount += p.farmerCount;
                        }
                      });
                    });

                    const summaries = Array.from(aggregated.values());
                    const grandTotal = {
                      farmerCount: summaries.reduce((s, p) => s + p.farmerCount, 0),
                      organicKg: summaries.reduce((s, p) => s + p.organicKg, 0),
                      conventionalKg: summaries.reduce((s, p) => s + p.conventionalKg, 0),
                      totalKg: summaries.reduce((s, p) => s + p.totalKg, 0),
                    };

                    return (
                      <>
                        {summaries.map(p => (
                          <TableRow key={p.pengepulId}>
                            <TableCell className="font-medium">{p.pengepulName}</TableCell>
                            <TableCell className="text-right">{p.farmerCount}</TableCell>
                            <TableCell className="text-right text-green-700">{p.organicKg.toLocaleString()}</TableCell>
                            <TableCell className="text-right text-orange-700">{p.conventionalKg.toLocaleString()}</TableCell>
                            <TableCell className="text-right font-bold">{p.totalKg.toLocaleString()}</TableCell>
                          </TableRow>
                        ))}
                        <TableRow className="bg-muted/50 font-bold">
                          <TableCell>Grand Total</TableCell>
                          <TableCell className="text-right">{grandTotal.farmerCount}</TableCell>
                          <TableCell className="text-right text-green-700">{grandTotal.organicKg.toLocaleString()}</TableCell>
                          <TableCell className="text-right text-orange-700">{grandTotal.conventionalKg.toLocaleString()}</TableCell>
                          <TableCell className="text-right">{grandTotal.totalKg.toLocaleString()}</TableCell>
                        </TableRow>
                      </>
                    );
                  })()}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
};
