// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-farmers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_farmers_default = defineTool({
  name: "list_farmers",
  title: "List farmers",
  description: "List petani (farmers) registered in the koperasi, including their kode_petani, name, and assigned pengepul (collector).",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive filter matched against kode_petani or nama_petani."),
    limit: z.number().int().min(1).max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("petani").select("id, kode_petani, nama_petani, alamat, no_hp, pengepul_id, pengepul(nama_pengepul, kode_pengepul)").order("kode_petani", { ascending: true }).limit(limit);
    if (search && search.trim()) {
      const s = search.trim();
      query = query.or(`kode_petani.ilike.%${s}%,nama_petani.ilike.%${s}%`);
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { farmers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-batches.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_batches_default = defineTool2({
  name: "list_batches",
  title: "List harvest batches",
  description: "List batch_panen (harvest receiving batches) for the koperasi. Returns batch_number, tanggal, total_berat, and status.",
  inputSchema: {
    status: z2.string().optional().describe("Optional status filter (e.g. 'pending', 'selesai')."),
    limit: z2.number().int().min(1).max(500).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("batch_panen").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { batches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/warehouse-stock.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var warehouse_stock_default = defineTool3({
  name: "warehouse_stock",
  title: "Warehouse stock",
  description: "Return current gudang (warehouse) stock records with weights and batch references.",
  inputSchema: {
    limit: z3.number().int().min(1).max(1e3).default(200)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("gudang_stok").select("*").order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const totalBerat = (data ?? []).reduce(
      (acc, row) => acc + Number(row.berat_kg ?? row.stok_kg ?? 0),
      0
    );
    return {
      content: [
        {
          type: "text",
          text: `Total ${data?.length ?? 0} record, total berat ${totalBerat.toFixed(1)} Kg`
        }
      ],
      structuredContent: { total_berat_kg: totalBerat, stock: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/trace-product.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.23.8";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var trace_product_default = defineTool4({
  name: "trace_product",
  title: "Trace product code",
  description: "Trace a product identity code (e.g. BN6-201025-001) across penjualan_petani, batch_panen, proses_pengeringan, and gudang_stok stages.",
  inputSchema: {
    product_code: z4.string().min(3).describe("The product identity code to trace, e.g. 'BN6-201025-001'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ product_code }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const pattern = `%${product_code}%`;
    const [sales, batches, drying, stock] = await Promise.all([
      supabase.from("penjualan_petani").select("*").ilike("detail_petani::text", pattern).limit(50),
      supabase.from("batch_panen").select("*").ilike("detail_petani::text", pattern).limit(50),
      supabase.from("proses_pengeringan").select("*").ilike("detail_batch::text", pattern).limit(50),
      supabase.from("gudang_stok").select("*").ilike("detail::text", pattern).limit(50)
    ]);
    const stages = {
      penjualan_petani: sales.data ?? [],
      batch_panen: batches.data ?? [],
      proses_pengeringan: drying.data ?? [],
      gudang_stok: stock.data ?? []
    };
    const found = Object.entries(stages).filter(([, rows]) => rows.length > 0).map(([stage, rows]) => `${stage}: ${rows.length}`).join(", ");
    return {
      content: [
        { type: "text", text: found ? `Found in ${found}` : "No trace matches found." }
      ],
      structuredContent: { product_code, stages }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kreupbnakmqgfsbiijhl";
var mcp_default = defineMcp({
  name: "bgm-koperasi-mcp",
  title: "Berkah Gendis Mandiri Koperasi MCP",
  version: "0.1.0",
  instructions: "Tools for the BGM koperasi harvest management system. Use `list_farmers` to browse petani, `list_batches` for penerimaan gudang, `warehouse_stock` for current gudang stock, and `trace_product` to trace a product identity code across the supply chain.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_farmers_default, list_batches_default, warehouse_stock_default, trace_product_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
